export interface NewTemplateData {
  id: string;
  type: string; // Category name
  category: string;
  title: string;
  subtitle: string;
  date: string;
  time: string;
  host: string;
  venue: string;
  gradient: string;
  accentColor: string;
  emoji: string;
  image: string;
  description: string;
  backgroundColor: string;
  textColor: string;
  titleSize: number;
  fontWeight: string;
  fontFamily: string;
  buttonColor: string;
  buttonRadius: number;
  buttonText: string;
  textAlignment: string;
  gallery: string[];
  sections: { title: string; content: string }[];
}

export const NEW_TEMPLATES: NewTemplateData[] = [
  // ==================== WEDDING (10) ====================
  {
    id: "tpl-wedding-1",
    type: "Wedding",
    category: "Wedding",
    title: "Celestial Romance Vows",
    subtitle: "Together with their families",
    date: "Sat, Sept 12",
    time: "4:30 PM",
    host: "Hosted by Eleanor & Julian",
    venue: "Starlight Estate & Conservatory",
    gradient: "linear-gradient(135deg, #fdfcfb 0%, #e2d1c3 100%)",
    accentColor: "#d4af37",
    emoji: "💍",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    description: "Join us for an enchanting evening of love, laughter, and lifelong memories under the stars.",
    backgroundColor: "#FAF8F5",
    textColor: "#2D1B3D",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#d4af37",
    buttonRadius: 12,
    buttonText: "RSVP to Ceremony",
    textAlignment: "center",
    gallery: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80"
    ],
    sections: [
      { title: "Schedule", content: "4:30 PM Ceremony | 6:00 PM Cocktails | 7:00 PM Dinner & Dancing" },
      { title: "Dress Code", content: "Black Tie Optional" }
    ]
  },
  {
    id: "tpl-wedding-2",
    type: "Wedding",
    category: "Wedding",
    title: "Botanical Glasshouse Union",
    subtitle: "Celebrate our new beginning",
    date: "Sun, Oct 18",
    time: "3:00 PM",
    host: "Hosted by Chloe & Marcus",
    venue: "The Orchid Glasshouse Gardens",
    gradient: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    accentColor: "#2e7d32",
    emoji: "🌿",
    image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
    description: "Step into our serene botanical sanctuary as we exchange vows surrounded by lush greenery.",
    backgroundColor: "#F4F7F4",
    textColor: "#1C351E",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#2e7d32",
    buttonRadius: 10,
    buttonText: "RSVP Now",
    textAlignment: "center",
    gallery: [
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80"
    ],
    sections: [
      { title: "Accommodations", content: "Block reserved at Botanica Resort & Spa." }
    ]
  },
  {
    id: "tpl-wedding-3",
    type: "Wedding",
    category: "Wedding",
    title: "Sunset Oceanfront Vows",
    subtitle: "Love as endless as the ocean",
    date: "Fri, Nov 6",
    time: "5:15 PM",
    host: "Hosted by Maya & Jonathan",
    venue: "Malibu Cove Ocean Villa",
    gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    accentColor: "#e06d53",
    emoji: "🌅",
    image: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=80",
    description: "Witness our promises at golden hour along the sun-kissed shores of Malibu Beach.",
    backgroundColor: "#FFF9F5",
    textColor: "#3A2219",
    titleSize: 50,
    fontWeight: "700",
    fontFamily: "Great Vibes",
    buttonColor: "#e06d53",
    buttonRadius: 14,
    buttonText: "Join Us Beachside",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-4",
    type: "Wedding",
    category: "Wedding",
    title: "Minimalist Modern Love",
    subtitle: "Two hearts, one story",
    date: "Sat, Dec 5",
    time: "6:00 PM",
    host: "Hosted by Sophia & David",
    venue: "The Loft Contemporary Gallery",
    gradient: "linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 100%)",
    accentColor: "#333333",
    emoji: "🕊️",
    image: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80",
    description: "An elegant, minimalist celebration of partnership, fine art, and contemporary design.",
    backgroundColor: "#FAFAFA",
    textColor: "#111111",
    titleSize: 44,
    fontWeight: "600",
    fontFamily: "Inter",
    buttonColor: "#222222",
    buttonRadius: 6,
    buttonText: "Confirm Attendance",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-5",
    type: "Wedding",
    category: "Wedding",
    title: "Rustic Terracotta Barn Wedding",
    subtitle: "Warmth, laughter, and happily ever after",
    date: "Sat, Sept 26",
    time: "3:30 PM",
    host: "Hosted by Hannah & Tyler",
    venue: "Whispering Pines Heritage Barn",
    gradient: "linear-gradient(135deg, #f7d6c8 0%, #e59882 100%)",
    accentColor: "#b85636",
    emoji: "🌾",
    image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=80",
    description: "Gather with us in the cozy countryside for a rustic dinner, live acoustic music, and barn dancing.",
    backgroundColor: "#FAF4F0",
    textColor: "#3D241C",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Merriweather",
    buttonColor: "#b85636",
    buttonRadius: 10,
    buttonText: "RSVP Today",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-6",
    type: "Wedding",
    category: "Wedding",
    title: "Vintage European Chateau Affair",
    subtitle: "A fairytale story unfolds",
    date: "Sat, Oct 10",
    time: "4:00 PM",
    host: "Hosted by Isabelle & Henri",
    venue: "Chateau Grandeur Courtyard",
    gradient: "linear-gradient(135deg, #ede7f6 0%, #d1c4e9 100%)",
    accentColor: "#673ab7",
    emoji: "🏰",
    image: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80",
    description: "An romantic evening inspired by classic European elegance, fine wine, and candlelit waltzes.",
    backgroundColor: "#F7F5FA",
    textColor: "#261738",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#673ab7",
    buttonRadius: 12,
    buttonText: "Reserve Your Spot",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-7",
    type: "Wedding",
    category: "Wedding",
    title: "Royal Navy & Gold Gala",
    subtitle: "Honoring our eternal commitment",
    date: "Sat, Nov 21",
    time: "5:00 PM",
    host: "Hosted by Victoria & Alexander",
    venue: "The Imperial Palace Ballroom",
    gradient: "linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)",
    accentColor: "#ffd700",
    emoji: "👑",
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80",
    description: "A majestic black-tie affair filled with opulent gold decor, gourmet dining, and royal festivities.",
    backgroundColor: "#0B132B",
    textColor: "#F4F5F6",
    titleSize: 50,
    fontWeight: "800",
    fontFamily: "Playfair Display",
    buttonColor: "#ffd700",
    buttonRadius: 8,
    buttonText: "Accept Invitation",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-8",
    type: "Wedding",
    category: "Wedding",
    title: "Bohemian Woodland Magic",
    subtitle: "Wildflowers & endless love",
    date: "Sun, Sept 20",
    time: "2:30 PM",
    host: "Hosted by Freya & Noah",
    venue: "Redwood Canopy Sanctuary",
    gradient: "linear-gradient(135deg, #d7ccc8 0%, #a1887f 100%)",
    accentColor: "#5d4037",
    emoji: "🌲",
    image: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80",
    description: "Under majestic redwood trees, join us for a whimsical bohemian wedding celebration.",
    backgroundColor: "#F5F2F0",
    textColor: "#2C1D18",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#5d4037",
    buttonRadius: 16,
    buttonText: "Join Vows",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-9",
    type: "Wedding",
    category: "Wedding",
    title: "Tropical Paradise Union",
    subtitle: "Love in full bloom",
    date: "Sat, Jan 16",
    time: "4:00 PM",
    host: "Hosted by Leilani & Kai",
    venue: "Bali Palm Beach Villa",
    gradient: "linear-gradient(135deg, #e0f7fa 0%, #80deea 100%)",
    accentColor: "#00838f",
    emoji: "🌺",
    image: "https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1200&q=80",
    description: "Island breeze, ocean acoustic music, and tropical cocktails as we tie the knot in paradise.",
    backgroundColor: "#F0FAFC",
    textColor: "#00363A",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#00838f",
    buttonRadius: 12,
    buttonText: "RSVP to Paradise",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-wedding-10",
    type: "Wedding",
    category: "Wedding",
    title: "Classic Rose Gold Romance",
    subtitle: "Forever begins today",
    date: "Sat, Feb 13",
    time: "5:30 PM",
    host: "Hosted by Olivia & William",
    venue: "The Rosewood Hotel Ballroom",
    gradient: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
    accentColor: "#c2185b",
    emoji: "🌹",
    image: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1200&q=80",
    description: "Celebrate our eternal bond with a romantic dinner, champagne toast, and classic waltz.",
    backgroundColor: "#FAF2F5",
    textColor: "#3B081B",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#c2185b",
    buttonRadius: 12,
    buttonText: "RSVP Now",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== BABY SHOWER (10) ====================
  {
    id: "tpl-babyshower-1",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Little Starry Night Shower",
    subtitle: "Twinkle, twinkle little star",
    date: "Sat, Aug 22",
    time: "1:00 PM",
    host: "Hosted by The Miller Family",
    venue: "Starlight Garden Cafe",
    gradient: "linear-gradient(135deg, #e1f5fe 0%, #b3e5fc 100%)",
    accentColor: "#0288d1",
    emoji: "⭐",
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=80",
    description: "Help us welcome our little shining star with sweet treats, fun baby trivia, and joyful gifts!",
    backgroundColor: "#F4FAFD",
    textColor: "#013755",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Poppins",
    buttonColor: "#0288d1",
    buttonRadius: 12,
    buttonText: "RSVP to Shower",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-2",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Woodland Forest Friends Shower",
    subtitle: "A wild little adventure is beginning",
    date: "Sun, Sept 13",
    time: "12:30 PM",
    host: "Hosted by Sarah & Benjamin",
    venue: "Pinewood Lodge Pavilion",
    gradient: "linear-gradient(135deg, #d7ccc8 0%, #bcaaa4 100%)",
    accentColor: "#4e342e",
    emoji: "🦊",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1200&q=80",
    description: "Join us in welcoming our cozy woodland miracle with rustic games, hot cocoa, and sweet memories.",
    backgroundColor: "#FAF7F5",
    textColor: "#2C1B17",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#4e342e",
    buttonRadius: 10,
    buttonText: "Count Me In",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-3",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Pastel Balloon Fiesta Shower",
    subtitle: "Pop the champagne, baby is on the way!",
    date: "Sat, Oct 17",
    time: "2:00 PM",
    host: "Hosted by Jessica & Friends",
    venue: "Sunshine Tea House",
    gradient: "linear-gradient(135deg, #f8bbd0 0%, #e1bee7 100%)",
    accentColor: "#ab47bc",
    emoji: "🎈",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80",
    description: "A whimsical afternoon filled with pastel balloons, afternoon high tea, and baby shower games.",
    backgroundColor: "#FCF6FD",
    textColor: "#380E40",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#ab47bc",
    buttonRadius: 14,
    buttonText: "Join the Party",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-4",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Teddy Bear Picnic Shower",
    subtitle: "Warm, cuddly, and oh so sweet!",
    date: "Sun, Nov 8",
    time: "11:30 AM",
    host: "Hosted by Grandma Rose",
    venue: "Sunny Meadows Park",
    gradient: "linear-gradient(135deg, #fff8e1 0%, #ffecb3 100%)",
    accentColor: "#ff8f00",
    emoji: "🧸",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
    description: "Bring your favorite teddy bear memories and celebrate baby's upcoming arrival under the oak trees.",
    backgroundColor: "#FFFCF5",
    textColor: "#4A2B00",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Merriweather",
    buttonColor: "#ff8f00",
    buttonRadius: 12,
    buttonText: "RSVP to Picnic",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-5",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Under the Sea Splash Shower",
    subtitle: "Making a splash in our hearts",
    date: "Sat, Aug 29",
    time: "3:00 PM",
    host: "Hosted by Emily & Mark",
    venue: "Ocean Vista Hall",
    gradient: "linear-gradient(135deg, #e0f2f1 0%, #80cbd4 100%)",
    accentColor: "#00695c",
    emoji: "🐬",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    description: "Dive into a cute nautical baby shower with sea-themed treats, refreshing drinks, and ocean vibes.",
    backgroundColor: "#F2FAF9",
    textColor: "#002B26",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#00695c",
    buttonRadius: 10,
    buttonText: "RSVP Now",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-6",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Floral Garden Bloom Shower",
    subtitle: "Our little blossom is on the way",
    date: "Sun, Sept 27",
    time: "1:30 PM",
    host: "Hosted by The Floral Sisterhood",
    venue: "Rosewood Botanical Tea Garden",
    gradient: "linear-gradient(135deg, #fce4ec 0%, #f48fb1 100%)",
    accentColor: "#ad1457",
    emoji: "🌸",
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1200&q=80",
    description: "Celebrate amidst blooming roses and floral garlands with gourmet finger sandwiches and lemonade.",
    backgroundColor: "#FAF2F5",
    textColor: "#420019",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ad1457",
    buttonRadius: 12,
    buttonText: "RSVP to Bloom",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-7",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Over the Rainbow Shower",
    subtitle: "Promises of joy and sunshine",
    date: "Sat, Oct 24",
    time: "2:00 PM",
    host: "Hosted by Laura & Friends",
    venue: "Skylight Conservatory",
    gradient: "linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)",
    accentColor: "#f57c00",
    emoji: "🌈",
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
    description: "A bright rainbow-themed baby shower filled with vibrant colors, sweet pastries, and laughter.",
    backgroundColor: "#FFFDF7",
    textColor: "#3E1E00",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#f57c00",
    buttonRadius: 12,
    buttonText: "Confirm Attendance",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  {
    id: "tpl-babyshower-9",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Cloud & Moon Starlight Shower",
    subtitle: "Dream big, little one",
    date: "Sat, Dec 12",
    time: "4:00 PM",
    host: "Hosted by The Carter Family",
    venue: "Heavenly Heights Terrace",
    gradient: "linear-gradient(135deg, #e8eaf6 0%, #c5cae9 100%)",
    accentColor: "#3f51b5",
    emoji: "🌙",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    description: "An evening moonlit baby shower with fluffy white cloud decorations and starry twinkling lights.",
    backgroundColor: "#F5F6FA",
    textColor: "#121A42",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Poppins",
    buttonColor: "#3f51b5",
    buttonRadius: 12,
    buttonText: "Reserve Seat",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-babyshower-10",
    type: "Baby Shower",
    category: "Baby Shower",
    title: "Safari Jungle Adventure Shower",
    subtitle: "Welcome to the wild world!",
    date: "Sat, Jan 23",
    time: "1:00 PM",
    host: "Hosted by Daniel & Amanda",
    venue: "Wildwood Eco Lodge",
    gradient: "linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)",
    accentColor: "#388e3c",
    emoji: "🦁",
    image: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80",
    description: "A fun jungle safari baby shower featuring adorable animal decor, tropical punch, and games.",
    backgroundColor: "#F4FAF5",
    textColor: "#0E2B0F",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#388e3c",
    buttonRadius: 12,
    buttonText: "RSVP Safari",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== CORPORATE (10) ====================
  {
    id: "tpl-corporate-1",
    type: "Corporate",
    category: "Corporate",
    title: "Tech Summit & Keynote 2026",
    subtitle: "Architecting the Future of AI",
    date: "Thu, Sept 24",
    time: "9:00 AM",
    host: "Hosted by Nexus AI Labs",
    venue: "Silicon Convention Center",
    gradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    accentColor: "#38bdf8",
    emoji: "💻",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    description: "Connect with global industry leaders, tech visionaries, and venture capitalists shaping the tech ecosystem.",
    backgroundColor: "#0F172A",
    textColor: "#F8FAFC",
    titleSize: 44,
    fontWeight: "800",
    fontFamily: "Inter",
    buttonColor: "#38bdf8",
    buttonRadius: 8,
    buttonText: "Register for Summit",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-2",
    type: "Corporate",
    category: "Corporate",
    title: "Executive Leadership Retreat",
    subtitle: "Vision, Strategy & Growth",
    date: "Fri, Oct 16",
    time: "8:30 AM",
    host: "Hosted by Apex Global Corp",
    venue: "Mountain Peak Eco Resort",
    gradient: "linear-gradient(135deg, #1c3144 0%, #000000 100%)",
    accentColor: "#d00000",
    emoji: "🏔️",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    description: "An exclusive weekend retreat focusing on executive alignment, high-stakes decision making, and wellness.",
    backgroundColor: "#111827",
    textColor: "#F9FAFB",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#d00000",
    buttonRadius: 8,
    buttonText: "Confirm Attendance",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-3",
    type: "Corporate",
    category: "Corporate",
    title: "Global Investor Pitch Night",
    subtitle: "Empowering Next-Gen Disruptors",
    date: "Wed, Nov 11",
    time: "6:30 PM",
    host: "Hosted by Wall Street Venture Fund",
    venue: "Wall Street Tower - 50th Fl",
    gradient: "linear-gradient(135deg, #2c3e50 0%, #000000 100%)",
    accentColor: "#f1c40f",
    emoji: "📈",
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80",
    description: "Top 10 pre-Series A tech startups present to leading angel investors, institutional VC funds, and partners.",
    backgroundColor: "#161F28",
    textColor: "#FFFFFF",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#f1c40f",
    buttonRadius: 6,
    buttonText: "Request Pass",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-4",
    type: "Corporate",
    category: "Corporate",
    title: "AI Innovation Expo",
    subtitle: "Pioneering Next-Gen Intelligence",
    date: "Tue, Dec 1",
    time: "10:00 AM",
    host: "Hosted by CyberTech Alliance",
    venue: "Metropolitan Cybertech Auditorium",
    gradient: "linear-gradient(135deg, #4a148c 0%, #12005e 100%)",
    accentColor: "#00e5ff",
    emoji: "🤖",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
    description: "Discover hands-on AI demonstrations, autonomous robotics, generative models, and enterprise software.",
    backgroundColor: "#0D0221",
    textColor: "#F0F4F8",
    titleSize: 44,
    fontWeight: "800",
    fontFamily: "Outfit",
    buttonColor: "#00e5ff",
    buttonRadius: 8,
    buttonText: "Claim Free Ticket",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-5",
    type: "Corporate",
    category: "Corporate",
    title: "Annual Corporate Excellence Awards",
    subtitle: "Celebrating Innovators & Trailblazers",
    date: "Fri, Dec 18",
    time: "7:00 PM",
    host: "Hosted by Enterprise Council",
    venue: "Starlight Grand Ballroom",
    gradient: "linear-gradient(135deg, #b71c1c 0%, #560027 100%)",
    accentColor: "#ffb300",
    emoji: "🏆",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
    description: "An elegant black-tie gala honoring extraordinary achievements, leadership milestones, and team success.",
    backgroundColor: "#1A0508",
    textColor: "#FFF8E7",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ffb300",
    buttonRadius: 8,
    buttonText: "RSVP to Gala",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-6",
    type: "Corporate",
    category: "Corporate",
    title: "Product Launch Showcase",
    subtitle: "Unveiling the Future of Cloud Infrastructure",
    date: "Thu, Oct 29",
    time: "5:30 PM",
    host: "Hosted by CloudScale Tech",
    venue: "Metropolitan Loft 44",
    gradient: "linear-gradient(135deg, #263238 0%, #000000 100%)",
    accentColor: "#ff6d00",
    emoji: "🚀",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
    description: "Live product demonstrations, keynote presentations from founders, and exclusive networking over cocktails.",
    backgroundColor: "#12191D",
    textColor: "#ECEFF1",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#ff6d00",
    buttonRadius: 8,
    buttonText: "RSVP VIP Pass",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-7",
    type: "Corporate",
    category: "Corporate",
    title: "Corporate Sustainability Forum",
    subtitle: "Net-Zero Strategies for 2030",
    date: "Wed, Sept 30",
    time: "9:30 AM",
    host: "Hosted by Green Earth Enterprise",
    venue: "Eco Park Innovation Hub",
    gradient: "linear-gradient(135deg, #1b5e20 0%, #003300 100%)",
    accentColor: "#66bb6a",
    emoji: "🌱",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    description: "Join Fortune 500 executives and sustainability leaders discussing renewable energy, carbon offset, and ESG.",
    backgroundColor: "#0B1D0D",
    textColor: "#E8F5E9",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#66bb6a",
    buttonRadius: 8,
    buttonText: "Reserve Seat",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-8",
    type: "Corporate",
    category: "Corporate",
    title: "Fintech Breakthrough Summit",
    subtitle: "Decentralized Finance & Banking 3.0",
    date: "Tue, Nov 17",
    time: "10:00 AM",
    host: "Hosted by Capital One Network",
    venue: "Fintech Center Auditorium",
    gradient: "linear-gradient(135deg, #0d47a1 0%, #002171 100%)",
    accentColor: "#29b6f6",
    emoji: "💳",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    description: "Explore the latest breakthroughs in digital payments, blockchain infrastructure, and banking security.",
    backgroundColor: "#06152D",
    textColor: "#E1F5FE",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#29b6f6",
    buttonRadius: 8,
    buttonText: "Get Access Pass",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-9",
    type: "Corporate",
    category: "Corporate",
    title: "Design & UX Thought Leadership",
    subtitle: "Crafting Human-Centric Experiences",
    date: "Fri, Oct 23",
    time: "2:00 PM",
    host: "Hosted by Creative Design Guild",
    venue: "Modernist Design Studio",
    gradient: "linear-gradient(135deg, #37474f 0%, #102027 100%)",
    accentColor: "#ff4081",
    emoji: "🎨",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    description: "Workshops and roundtables on design systems, micro-interactions, and accessibility in digital products.",
    backgroundColor: "#182226",
    textColor: "#ECEFF1",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#ff4081",
    buttonRadius: 10,
    buttonText: "Join Workshop",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-corporate-10",
    type: "Corporate",
    category: "Corporate",
    title: "Venture Partner Private Dinner",
    subtitle: "An intimate evening with founders & partners",
    date: "Thu, Nov 19",
    time: "7:00 PM",
    host: "Hosted by Horizon Ventures",
    venue: "Penthouse 54 Lounge",
    gradient: "linear-gradient(135deg, #212121 0%, #000000 100%)",
    accentColor: "#e040fb",
    emoji: "🍸",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    description: "An exclusive invite-only dinner for fund partners and unicorn founders to discuss strategic investments.",
    backgroundColor: "#121212",
    textColor: "#FAFAFA",
    titleSize: 44,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#e040fb",
    buttonRadius: 8,
    buttonText: "RSVP VIP Dinner",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== BIRTHDAY (10) ====================
  {
    id: "tpl-birthday-1",
    type: "Birthday",
    category: "Birthday",
    title: "Neon Glow Birthday Bash",
    subtitle: "Turn up the lights and turn up the fun!",
    date: "Sat, Aug 29",
    time: "9:00 PM",
    host: "Hosted by Alex & Crew",
    venue: "Club Velocity Lounge",
    gradient: "linear-gradient(135deg, #880e4f 0%, #4a148c 100%)",
    accentColor: "#ff4081",
    emoji: "⚡",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    description: "Wear your brightest neon outfit and dance all night with live DJ sets, laser lights, and glowing cocktails!",
    backgroundColor: "#1E041B",
    textColor: "#FCE4EC",
    titleSize: 48,
    fontWeight: "800",
    fontFamily: "Outfit",
    buttonColor: "#ff4081",
    buttonRadius: 14,
    buttonText: "RSVP to Party",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-2",
    type: "Birthday",
    category: "Birthday",
    title: "Sweet 16 Sparkle Celebration",
    subtitle: "Shine bright like a diamond",
    date: "Sat, Sept 19",
    time: "6:00 PM",
    host: "Hosted by The Davis Family",
    venue: "Crystal Ballroom",
    gradient: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
    accentColor: "#ec407a",
    emoji: "✨",
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
    description: "Join Samantha for a glamorous Sweet 16 celebration featuring a red carpet entrance, photo booth, and dessert bar.",
    backgroundColor: "#FAF0F4",
    textColor: "#380617",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ec407a",
    buttonRadius: 12,
    buttonText: "RSVP to Sparkle",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-3",
    type: "Birthday",
    category: "Birthday",
    title: "Golden 50th Jubilee Birthday",
    subtitle: "50 Years of Memories & Grace",
    date: "Sun, Oct 11",
    time: "5:00 PM",
    host: "Hosted by Robert's Children",
    venue: "Grand Heritage Hotel",
    gradient: "linear-gradient(135deg, #fff8e1 0%, #ffecb3 100%)",
    accentColor: "#ffb300",
    emoji: "🥂",
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80",
    description: "Honor five golden decades with fine wine, live jazz performance, and a retrospective photo slideshow.",
    backgroundColor: "#FFFDF7",
    textColor: "#3B2700",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#ffb300",
    buttonRadius: 10,
    buttonText: "Toast to Robert",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-4",
    type: "Birthday",
    category: "Birthday",
    title: "Retro 80s Disco Birthday",
    subtitle: "Break out the leg warmers & neon!",
    date: "Fri, Nov 13",
    time: "8:00 PM",
    host: "Hosted by Marcus & Friends",
    venue: "Rollerland Lounge",
    gradient: "linear-gradient(135deg, #00b0ff 0%, #aa00ff 100%)",
    accentColor: "#00e5ff",
    emoji: "🪩",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
    description: "A throwback 80s roller disco party with synth-pop hits, arcade games, and vintage cocktails.",
    backgroundColor: "#0D041E",
    textColor: "#E1F5FE",
    titleSize: 48,
    fontWeight: "800",
    fontFamily: "Poppins",
    buttonColor: "#00e5ff",
    buttonRadius: 16,
    buttonText: "Get Your Pass",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-5",
    type: "Birthday",
    category: "Birthday",
    title: "Tropical Poolside Birthday",
    subtitle: "Sun, swim, and birthday fun",
    date: "Sat, Aug 15",
    time: "2:00 PM",
    host: "Hosted by Chloe",
    venue: "Azure Palms Resort Pool",
    gradient: "linear-gradient(135deg, #e0f7fa 0%, #80deea 100%)",
    accentColor: "#00acc1",
    emoji: "🍹",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    description: "Beat the heat with cabana lounge chairs, tropical smoothies, pool floaties, and BBQ.",
    backgroundColor: "#F0FAFC",
    textColor: "#00363A",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#00acc1",
    buttonRadius: 12,
    buttonText: "RSVP Pool Party",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-6",
    type: "Birthday",
    category: "Birthday",
    title: "Wild Safari Kids Birthday",
    subtitle: "Leo is turning 4!",
    date: "Sat, Sept 26",
    time: "11:00 AM",
    host: "Hosted by The Johnson Family",
    venue: "Jungle Adventure Park",
    gradient: "linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)",
    accentColor: "#fb8c00",
    emoji: "🦒",
    image: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80",
    description: "Join us for a roar-some 4th birthday with face painting, pet zoo, and jungle cake!",
    backgroundColor: "#FFFDF7",
    textColor: "#3E1E00",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#fb8c00",
    buttonRadius: 12,
    buttonText: "Join Safari",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-7",
    type: "Birthday",
    category: "Birthday",
    title: "Cosmic Galaxy Birthday Bash",
    subtitle: "Out of this world celebrations",
    date: "Fri, Oct 23",
    time: "7:00 PM",
    host: "Hosted by Lucas",
    venue: "Stargazer Planetarium",
    gradient: "linear-gradient(135deg, #1a237e 0%, #311b92 100%)",
    accentColor: "#7c4dff",
    emoji: "🚀",
    image: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
    description: "Explore the cosmos with laser star shows, galaxy cupcakes, and space trivia.",
    backgroundColor: "#0D1137",
    textColor: "#EDE7F6",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#7c4dff",
    buttonRadius: 12,
    buttonText: "Launch RSVP",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-8",
    type: "Birthday",
    category: "Birthday",
    title: "Speakeasy Cocktail Birthday",
    subtitle: "Password required for entry",
    date: "Sat, Nov 7",
    time: "8:30 PM",
    host: "Hosted by Brandon",
    venue: "The Velvet Cellar Lounge",
    gradient: "linear-gradient(135deg, #263238 0%, #102027 100%)",
    accentColor: "#ffb74d",
    emoji: "🥃",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    description: "Step through the hidden doorway for craft cocktails, jazz piano, and a Prohibition-era celebration.",
    backgroundColor: "#141C20",
    textColor: "#FFF3E0",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#ffb74d",
    buttonRadius: 8,
    buttonText: "Get Secret Password",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-9",
    type: "Birthday",
    category: "Birthday",
    title: "Superhero Training Academy",
    subtitle: "Ethan's 6th Birthday Mission!",
    date: "Sat, Dec 5",
    time: "2:00 PM",
    host: "Hosted by The Hero Squad",
    venue: "Hero Action Zone",
    gradient: "linear-gradient(135deg, #b71c1c 0%, #0d47a1 100%)",
    accentColor: "#ffeb3b",
    emoji: "🦸‍♂️",
    image: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&w=1200&q=80",
    description: "Put on your favorite superhero cape for an obstacle course training, superhero cake, and prizes!",
    backgroundColor: "#160505",
    textColor: "#FFFDE7",
    titleSize: 46,
    fontWeight: "800",
    fontFamily: "Montserrat",
    buttonColor: "#ffeb3b",
    buttonRadius: 10,
    buttonText: "Report for Mission",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-birthday-10",
    type: "Birthday",
    category: "Birthday",
    title: "Enchanted Fairytale Garden",
    subtitle: "Where dreams and wishes come true",
    date: "Sun, Jan 17",
    time: "1:00 PM",
    host: "Hosted by Ella's Parents",
    venue: "Mystic Garden Pavilion",
    gradient: "linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)",
    accentColor: "#8e24aa",
    emoji: "🦄",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    description: "Fairy wings, magic wand craft tables, tea parties, and whimsical fairytale stories.",
    backgroundColor: "#FAF5FC",
    textColor: "#2D003B",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#8e24aa",
    buttonRadius: 12,
    buttonText: "RSVP to Magic",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== COMMUNITY (10) ====================
  {
    id: "tpl-community-1",
    type: "Community",
    category: "Community",
    title: "Neighborhood Summer BBQ",
    subtitle: "Good food, great neighbors",
    date: "Sat, Aug 15",
    time: "12:00 PM",
    host: "Hosted by Oakwood HOA",
    venue: "Oakwood Park Meadows",
    gradient: "linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)",
    accentColor: "#e65100",
    emoji: "🍔",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
    description: "Bring your favorite side dish! We'll provide grilled burgers, cold drinks, lawn games, and live music.",
    backgroundColor: "#FFFBF5",
    textColor: "#3A1400",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#e65100",
    buttonRadius: 10,
    buttonText: "RSVP to BBQ",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-2",
    type: "Community",
    category: "Community",
    title: "Community Farmers Market Day",
    subtitle: "Fresh local produce & artisan crafts",
    date: "Sat, Sept 5",
    time: "8:30 AM",
    host: "Hosted by Town Green Alliance",
    venue: "Town Center Plaza",
    gradient: "linear-gradient(135deg, #f1f8e9 0%, #c8e6c9 100%)",
    accentColor: "#33691e",
    emoji: "🍎",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1200&q=80",
    description: "Support local farmers and makers! Fresh organic vegetables, baked bread, artisanal honey, and live acoustic music.",
    backgroundColor: "#F7FAF5",
    textColor: "#13290B",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#33691e",
    buttonRadius: 8,
    buttonText: "Join Market",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-3",
    type: "Community",
    category: "Community",
    title: "Annual Block Party Celebration",
    subtitle: "Strengthening our neighborhood bonds",
    date: "Sat, Oct 3",
    time: "2:00 PM",
    host: "Hosted by Main St Neighbors",
    venue: "Main Street Pedestrian Zone",
    gradient: "linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%)",
    accentColor: "#1565c0",
    emoji: "🎈",
    image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80",
    description: "Bouncy castles for kids, food trucks, street chalk competition, and open mic performances.",
    backgroundColor: "#F4F9FD",
    textColor: "#062247",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#1565c0",
    buttonRadius: 12,
    buttonText: "Count Me In",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-4",
    type: "Community",
    category: "Community",
    title: "Green Earth Beach Cleanup",
    subtitle: "Protecting our oceans & coastlines",
    date: "Sun, Sept 20",
    time: "9:00 AM",
    host: "Hosted by Ocean Action Club",
    venue: "Sunset Cove Beach",
    gradient: "linear-gradient(135deg, #e0f2f1 0%, #b2dfdb 100%)",
    accentColor: "#00695c",
    emoji: "🌊",
    image: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=1200&q=80",
    description: "Join fellow environmental enthusiasts for a morning beach cleanup. Cleanup gloves and refreshments provided!",
    backgroundColor: "#F2FAF9",
    textColor: "#002B26",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#00695c",
    buttonRadius: 8,
    buttonText: "Volunteer Now",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-5",
    type: "Community",
    category: "Community",
    title: "Local Art & Craft Fair",
    subtitle: "Celebrating neighborhood creativity",
    date: "Sat, Nov 14",
    time: "10:00 AM",
    host: "Hosted by Civic Arts Guild",
    venue: "Community Arts Center",
    gradient: "linear-gradient(135deg, #f3e5f5 0%, #d1c4e9 100%)",
    accentColor: "#6a1b9a",
    emoji: "🎨",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
    description: "Discover handmade pottery, original paintings, handmade jewelry, and local woodwork from talented artists.",
    backgroundColor: "#FAF5FC",
    textColor: "#250538",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#6a1b9a",
    buttonRadius: 10,
    buttonText: "Get Free Pass",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-6",
    type: "Community",
    category: "Community",
    title: "Cultural Heritage Festival",
    subtitle: "Unity through diversity & traditions",
    date: "Sun, Oct 25",
    time: "11:00 AM",
    host: "Hosted by Cultural Diversity Council",
    venue: "Unity Heritage Park",
    gradient: "linear-gradient(135deg, #fff8e1 0%, #ffe082 100%)",
    accentColor: "#f57f17",
    emoji: "🌏",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80",
    description: "Experience vibrant international dance performances, traditional folk music, global food stalls, and workshops.",
    backgroundColor: "#FFFDF5",
    textColor: "#3D1E00",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#f57f17",
    buttonRadius: 12,
    buttonText: "RSVP to Festival",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  {
    id: "tpl-community-8",
    type: "Community",
    category: "Community",
    title: "Open Air Cinema Under Stars",
    subtitle: "Free outdoor movie & popcorn",
    date: "Sat, Sept 12",
    time: "7:30 PM",
    host: "Hosted by Parks & Rec",
    venue: "Central Park Amphitheater",
    gradient: "linear-gradient(135deg, #1a237e 0%, #121858 100%)",
    accentColor: "#ffca28",
    emoji: "🎬",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    description: "Pack lawn blankets and folding chairs for a family-friendly film screening under the stars. Free popcorn!",
    backgroundColor: "#0C1038",
    textColor: "#FFFDE7",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Poppins",
    buttonColor: "#ffca28",
    buttonRadius: 12,
    buttonText: "Reserve Spot",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-9",
    type: "Community",
    category: "Community",
    title: "Community Garden Harvest Festival",
    subtitle: "Sowing seeds, growing together",
    date: "Sun, Oct 18",
    time: "1:00 PM",
    host: "Hosted by Green Thumb Society",
    venue: "Green Thumb Gardens",
    gradient: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    accentColor: "#2e7d32",
    emoji: "🌻",
    image: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=1200&q=80",
    description: "Celebrate the autumn harvest with fresh cider, pumpkin painting, seed sharing workshops, and garden tours.",
    backgroundColor: "#F4FAF4",
    textColor: "#0B260C",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#2e7d32",
    buttonRadius: 10,
    buttonText: "RSVP to Harvest",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-community-10",
    type: "Community",
    category: "Community",
    title: "Holiday Toy & Food Drive",
    subtitle: "Spreading warmth & holiday cheer",
    date: "Sat, Dec 5",
    time: "10:00 AM",
    host: "Hosted by Community Care Network",
    venue: "Civic Community Hall",
    gradient: "linear-gradient(135deg, #ffebee 0%, #e8f5e9 100%)",
    accentColor: "#b71c1c",
    emoji: "🎁",
    image: "https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=1200&q=80",
    description: "Help us collect unwrapped toys and non-perishable food items for local families in need this holiday season.",
    backgroundColor: "#FAF5F5",
    textColor: "#2E0505",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Merriweather",
    buttonColor: "#b71c1c",
    buttonRadius: 10,
    buttonText: "Pledge Donation",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== NETWORKING (10) ====================
  {
    id: "tpl-networking-1",
    type: "Networking",
    category: "Networking",
    title: "Founders & Coffee Morning",
    subtitle: "Casual networking over artisanal brews",
    date: "Thu, Aug 27",
    time: "8:30 AM",
    host: "Hosted by Founder Collective",
    venue: "Roastery Social Loft",
    gradient: "linear-gradient(135deg, #efebe9 0%, #d7ccc8 100%)",
    accentColor: "#5d4037",
    emoji: "☕",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
    description: "An informal morning coffee social for startup founders, tech builders, and early-stage investors.",
    backgroundColor: "#FAF8F7",
    textColor: "#2A1C18",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#5d4037",
    buttonRadius: 8,
    buttonText: "Join Coffee Morning",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-2",
    type: "Networking",
    category: "Networking",
    title: "Women in Tech Leaders Summit",
    subtitle: "Inspire, Connect & Elevate",
    date: "Wed, Sept 16",
    time: "5:30 PM",
    host: "Hosted by WomenTech Global",
    venue: "Horizon Tower Auditorium",
    gradient: "linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)",
    accentColor: "#8e24aa",
    emoji: "👩‍💻",
    image: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?auto=format&fit=crop&w=1200&q=80",
    description: "Empowering keynote talks, mentorship speed-matching, and evening networking drinks with top female tech executives.",
    backgroundColor: "#FAF5FC",
    textColor: "#2D003B",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#8e24aa",
    buttonRadius: 10,
    buttonText: "Register Now",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-3",
    type: "Networking",
    category: "Networking",
    title: "Creative Directors Roundtable",
    subtitle: "Design, Branding & Visual Culture",
    date: "Thu, Oct 8",
    time: "6:30 PM",
    host: "Hosted by Design District Guild",
    venue: "Modernist Studio 4",
    gradient: "linear-gradient(135deg, #212121 0%, #424242 100%)",
    accentColor: "#ff6d00",
    emoji: "✒️",
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80",
    description: "An evening for art directors, UX leads, and brand strategists to discuss emerging creative trends.",
    backgroundColor: "#161616",
    textColor: "#FAFAFA",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#ff6d00",
    buttonRadius: 8,
    buttonText: "RSVP Roundtable",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-4",
    type: "Networking",
    category: "Networking",
    title: "Biotech & Healthcare Mixer",
    subtitle: "Innovations in Life Sciences",
    date: "Tue, Oct 20",
    time: "6:00 PM",
    host: "Hosted by BioHealth Alliance",
    venue: "Innovation Campus Hall",
    gradient: "linear-gradient(135deg, #e0f2f1 0%, #80cbc4 100%)",
    accentColor: "#00796b",
    emoji: "🧬",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    description: "Connecting medical researchers, pharma pioneers, and healthcare investors for prospective collaborations.",
    backgroundColor: "#F2FAF9",
    textColor: "#00332D",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#00796b",
    buttonRadius: 8,
    buttonText: "RSVP Mixer",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-5",
    type: "Networking",
    category: "Networking",
    title: "Real Estate Investor Night",
    subtitle: "Market Outlook & Property Deals",
    date: "Thu, Nov 12",
    time: "7:00 PM",
    host: "Hosted by Metro Realty Club",
    venue: "Metropolitan Sky Lounge",
    gradient: "linear-gradient(135deg, #1a237e 0%, #283593 100%)",
    accentColor: "#c0ca33",
    emoji: "🏢",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    description: "Network with commercial brokers, residential developers, private lenders, and REIT fund managers.",
    backgroundColor: "#0D113C",
    textColor: "#F9FBE7",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#c0ca33",
    buttonRadius: 8,
    buttonText: "Claim Investor Pass",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-6",
    type: "Networking",
    category: "Networking",
    title: "Startup Speed Networking",
    subtitle: "Find your co-founder or advisor",
    date: "Wed, Aug 19",
    time: "6:00 PM",
    host: "Hosted by Venture Launchpad",
    venue: "Venture Hub Co-working",
    gradient: "linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)",
    accentColor: "#1b5e20",
    emoji: "⚡",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    description: "Structured 5-minute speed networking rounds designed to connect technical developers with business strategists.",
    backgroundColor: "#F4FAF5",
    textColor: "#0A240C",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#1b5e20",
    buttonRadius: 8,
    buttonText: "Sign Up Now",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-7",
    type: "Networking",
    category: "Networking",
    title: "Global Professionals Evening",
    subtitle: "Expanding international horizons",
    date: "Fri, Sept 25",
    time: "7:00 PM",
    host: "Hosted by Expat Business Club",
    venue: "Skyline Regency Bar",
    gradient: "linear-gradient(135deg, #311b92 0%, #4527a0 100%)",
    accentColor: "#ffd54f",
    emoji: "🌐",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    description: "Join international expats, diplomats, and global business executives for an evening of networking and wine.",
    backgroundColor: "#130A3A",
    textColor: "#FFFDE7",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ffd54f",
    buttonRadius: 10,
    buttonText: "RSVP to Evening",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-8",
    type: "Networking",
    category: "Networking",
    title: "Young Professionals Social Mixer",
    subtitle: "Connect, collaborate & grow",
    date: "Thu, Oct 22",
    time: "6:30 PM",
    host: "Hosted by Metro YP Network",
    venue: "Urban Taphouse & Grill",
    gradient: "linear-gradient(135deg, #ffe0b2 0%, #ffcc80 100%)",
    accentColor: "#e65100",
    emoji: "🍻",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    description: "Relaxed happy hour networking for ambition-driven early-career professionals across all corporate sectors.",
    backgroundColor: "#FFFBF5",
    textColor: "#3A1400",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Poppins",
    buttonColor: "#e65100",
    buttonRadius: 12,
    buttonText: "Join Mixer",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-9",
    type: "Networking",
    category: "Networking",
    title: "Alumni Industry Network Night",
    subtitle: "Reconnect with fellow graduates",
    date: "Fri, Nov 20",
    time: "7:00 PM",
    host: "Hosted by University Alumni Board",
    venue: "The University Club",
    gradient: "linear-gradient(135deg, #880e4f 0%, #ad1457 100%)",
    accentColor: "#ff80ab",
    emoji: "🎓",
    image: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
    description: "Re-engage with university alumni across technology, finance, medicine, law, and arts industries.",
    backgroundColor: "#240415",
    textColor: "#FCE4EC",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#ff80ab",
    buttonRadius: 10,
    buttonText: "Confirm Attendance",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-networking-10",
    type: "Networking",
    category: "Networking",
    title: "Digital Nomads & Remote Tech Social",
    subtitle: "Work anywhere, connect everywhere",
    date: "Sat, Dec 12",
    time: "5:00 PM",
    host: "Hosted by Nomad Co-op",
    venue: "Coastal Sunset Bar",
    gradient: "linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%)",
    accentColor: "#0097a7",
    emoji: "🌴",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
    description: "Sunset drinks and casual networking for remote developers, freelancers, agency owners, and digital nomads.",
    backgroundColor: "#F0FAFC",
    textColor: "#003C43",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#0097a7",
    buttonRadius: 12,
    buttonText: "RSVP Nomad Social",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== PRIVATE DINNER (10) ====================
  {
    id: "tpl-privatedinner-1",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Chef's Wine & Tasting Dinner",
    subtitle: "A multi-course epicurean journey",
    date: "Fri, Sept 11",
    time: "7:30 PM",
    host: "Hosted by Chef Jean-Luc",
    venue: "La Maison Gourmet",
    gradient: "linear-gradient(135deg, #4a0072 0%, #2a003d 100%)",
    accentColor: "#e040fb",
    emoji: "🍷",
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80",
    description: "Indulge in a 7-course seasonal tasting menu expertly paired with rare vintage French wines.",
    backgroundColor: "#160022",
    textColor: "#FAFAFA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#e040fb",
    buttonRadius: 10,
    buttonText: "Reserve Seat",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-2",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Candlelit Garden Supper",
    subtitle: "Intimate dining amidst nature",
    date: "Sat, Oct 3",
    time: "7:00 PM",
    host: "Hosted by Amara & Friends",
    venue: "The Secret Courtyard",
    gradient: "linear-gradient(135deg, #33691e 0%, #1b5e20 100%)",
    accentColor: "#aed581",
    emoji: "🕯️",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    description: "Warm candlelit tables under olive trees, serving wood-fired artisanal cuisine and organic wines.",
    backgroundColor: "#0D1F08",
    textColor: "#F1F8E9",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#aed581",
    buttonRadius: 12,
    buttonText: "RSVP to Dinner",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-3",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Penthouse Sky Dining",
    subtitle: "High above the glowing city lights",
    date: "Fri, Nov 6",
    time: "8:00 PM",
    host: "Hosted by Executive Club",
    venue: "Penthouse 88 Lounge",
    gradient: "linear-gradient(135deg, #1c3144 0%, #0f172a 100%)",
    accentColor: "#ffb74d",
    emoji: "🌃",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    description: "Panoramics skyline views accompanied by caviar service, wagyu beef, and craft mixology.",
    backgroundColor: "#0B1220",
    textColor: "#FFF3E0",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#ffb74d",
    buttonRadius: 8,
    buttonText: "RSVP VIP Dining",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-4",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Tuscan Feast Under The Stars",
    subtitle: "Authentic Italian hospitality",
    date: "Sat, Sept 26",
    time: "6:30 PM",
    host: "Hosted by The Rossi Family",
    venue: "Vineyard Villa Terrace",
    gradient: "linear-gradient(135deg, #d84315 0%, #bf360c 100%)",
    accentColor: "#ffab91",
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
    description: "Handmade pasta, wood-roasted meats, freshly baked focaccia, and Chianti wine flow freely.",
    backgroundColor: "#2B0B03",
    textColor: "#FBE9E7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Merriweather",
    buttonColor: "#ffab91",
    buttonRadius: 10,
    buttonText: "Join Italian Feast",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-5",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Omakase Culinary Experience",
    subtitle: "Artistry of Japanese gastronomy",
    date: "Thu, Oct 22",
    time: "7:00 PM",
    host: "Hosted by Chef Master Kenji",
    venue: "Zen Sushi Atelier",
    gradient: "linear-gradient(135deg, #212121 0%, #000000 100%)",
    accentColor: "#e53935",
    emoji: "🍣",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80",
    description: "An exclusive 12-seat counter omakase experience featuring pristine seasonal seafood flown directly from Tokyo.",
    backgroundColor: "#121212",
    textColor: "#FFEBEE",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#e53935",
    buttonRadius: 6,
    buttonText: "Reserve Seat",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-6",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Speakeasy Secret Supper Club",
    subtitle: "Culinary secrets behind closed doors",
    date: "Fri, Nov 20",
    time: "8:30 PM",
    host: "Hosted by Culinary Society",
    venue: "Room 1920 Secret Parlor",
    gradient: "linear-gradient(135deg, #3e2723 0%, #1b0000 100%)",
    accentColor: "#d7ccc8",
    emoji: "🔑",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80",
    description: "Secret location disclosed 24 hours prior. Multi-course experimental dining with live jazz quartet.",
    backgroundColor: "#160C0A",
    textColor: "#EFEBE9",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#d7ccc8",
    buttonRadius: 10,
    buttonText: "Request Key",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-7",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Farm-to-Table Sunset Dinner",
    subtitle: "Pure ingredients, seasonal flavors",
    date: "Sat, Aug 22",
    time: "5:30 PM",
    host: "Hosted by Green Acre Farms",
    venue: "Organic Orchards Meadow",
    gradient: "linear-gradient(135deg, #f57f17 0%, #e65100 100%)",
    accentColor: "#ffe082",
    emoji: "🌾",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80",
    description: "Dine right alongside the harvest fields. Heirloom vegetables, pastured meats, and natural wines.",
    backgroundColor: "#2B1602",
    textColor: "#FFFDE7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#ffe082",
    buttonRadius: 12,
    buttonText: "RSVP Farm Dinner",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-privatedinner-8",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Seafood & Champagne Soirée",
    subtitle: "Coastal elegance & ocean breeze",
    date: "Sat, Oct 17",
    time: "7:00 PM",
    host: "Hosted by The Coastal Guild",
    venue: "Oceanfront Glass Villa",
    gradient: "linear-gradient(135deg, #00838f 0%, #004d40 100%)",
    accentColor: "#80deea",
    emoji: "🥂",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80",
    description: "Freshly shucked oysters, grilled lobster tails, and endless pours of vintage Brut champagne.",
    backgroundColor: "#031B1E",
    textColor: "#E0F7FA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#80deea",
    buttonRadius: 10,
    buttonText: "RSVP to Soirée",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  {
    id: "tpl-privatedinner-10",
    type: "Private Dinner",
    category: "Private Dinner",
    title: "Holiday Warmth Feast",
    subtitle: "Gather around the festive table",
    date: "Sat, Dec 19",
    time: "6:30 PM",
    host: "Hosted by The Sterling Family",
    venue: "Manor House Grand Dining Room",
    gradient: "linear-gradient(135deg, #b71c1c 0%, #1b5e20 100%)",
    accentColor: "#ffd700",
    emoji: "🕯️",
    image: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?auto=format&fit=crop&w=1200&q=80",
    description: "Roast turkey, mulled wine, crackling fireplace, and warm holiday toasts among close friends.",
    backgroundColor: "#1C0404",
    textColor: "#FFFDE7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Merriweather",
    buttonColor: "#ffd700",
    buttonRadius: 12,
    buttonText: "RSVP to Holiday Feast",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== FUNDRAISER (10) ====================
  {
    id: "tpl-fundraiser-1",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Hope & Healing Charity Gala",
    subtitle: "Empowering children's health & education",
    date: "Sat, Oct 10",
    time: "7:00 PM",
    host: "Hosted by Hope Foundation",
    venue: "Grand Marquis Ballroom",
    gradient: "linear-gradient(135deg, #004d40 0%, #00251a 100%)",
    accentColor: "#ffd54f",
    emoji: "✨",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
    description: "An elegant gala evening featuring live auctions, keynotes from medical pioneers, and black-tie dinner.",
    backgroundColor: "#021A15",
    textColor: "#FFFDE7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ffd54f",
    buttonRadius: 10,
    buttonText: "Purchase Ticket",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-2",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Save The Oceans Ocean Gala",
    subtitle: "Protecting marine ecosystems",
    date: "Sat, Sept 19",
    time: "6:30 PM",
    host: "Hosted by Blue Ocean Initiative",
    venue: "Maritime Museum Pavilion",
    gradient: "linear-gradient(135deg, #01579b 0%, #002f6c 100%)",
    accentColor: "#4fc3f7",
    emoji: "🐋",
    image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80",
    description: "Help raise funds for coral reef restoration and marine wildlife protection. Silent auction & dinner.",
    backgroundColor: "#021A30",
    textColor: "#E0F7FA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#4fc3f7",
    buttonRadius: 8,
    buttonText: "Support Oceans",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-3",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Wildlife Conservation Benefit",
    subtitle: "Preserving natural habitats worldwide",
    date: "Fri, Nov 13",
    time: "7:00 PM",
    host: "Hosted by World Wildlife Alliance",
    venue: "Natural History Pavilion",
    gradient: "linear-gradient(135deg, #33691e 0%, #1b5e20 100%)",
    accentColor: "#ffb74d",
    emoji: "🐅",
    image: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80",
    description: "Raising funds for anti-poaching teams and endangered species habitat conservation.",
    backgroundColor: "#0A1F08",
    textColor: "#FFF3E0",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#ffb74d",
    buttonRadius: 10,
    buttonText: "Donate & Attend",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-4",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Children's Health Gala Night",
    subtitle: "Every child deserves a healthy future",
    date: "Sat, Dec 5",
    time: "6:00 PM",
    host: "Hosted by St. Jude Auxiliary",
    venue: "St. Jude Convention Center",
    gradient: "linear-gradient(135deg, #880e4f 0%, #4a0072 100%)",
    accentColor: "#ff4081",
    emoji: "❤️",
    image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1200&q=80",
    description: "100% of ticket sales go directly toward pediatric cancer research and patient care.",
    backgroundColor: "#1F0314",
    textColor: "#FCE4EC",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#ff4081",
    buttonRadius: 12,
    buttonText: "Buy Gala Ticket",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-5",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Clean Water Initiative Gala",
    subtitle: "Bringing safe drinking water to communities",
    date: "Fri, Oct 30",
    time: "7:00 PM",
    host: "Hosted by Pure Water Fund",
    venue: "Aquatic Palace Hall",
    gradient: "linear-gradient(135deg, #00838f 0%, #004d40 100%)",
    accentColor: "#80deea",
    emoji: "💧",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    description: "An inspiring evening dedicated to building clean water wells in drought-affected rural villages.",
    backgroundColor: "#031C1F",
    textColor: "#E0F7FA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#80deea",
    buttonRadius: 8,
    buttonText: "RSVP to Gala",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-6",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Arts & Culture Foundation Ball",
    subtitle: "Sustaining theater, dance & music",
    date: "Sat, Nov 21",
    time: "7:30 PM",
    host: "Hosted by Civic Arts Endowment",
    venue: "Symphony Hall Rotunda",
    gradient: "linear-gradient(135deg, #311b92 0%, #1a237e 100%)",
    accentColor: "#ffd700",
    emoji: "🎻",
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1200&q=80",
    description: "Live orchestral performances, ballet showcases, and silent art auction in support of youth art programs.",
    backgroundColor: "#0F0933",
    textColor: "#FFFDE7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ffd700",
    buttonRadius: 10,
    buttonText: "Reserve Ball Seat",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-7",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Scholarship Fund Golf Classic",
    subtitle: "Tee off for higher education",
    date: "Sat, Aug 22",
    time: "8:00 AM",
    host: "Hosted by Higher Ed Foundation",
    venue: "Greenbrier Country Club",
    gradient: "linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%)",
    accentColor: "#ffeb3b",
    emoji: "⛳",
    image: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80",
    description: "18-hole scramble tournament, lunch buffet, award ceremony, and silent auction raising college scholarships.",
    backgroundColor: "#0B260D",
    textColor: "#FFFDE7",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#ffeb3b",
    buttonRadius: 8,
    buttonText: "Register Foursome",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-8",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Empower Women Leadership Gala",
    subtitle: "Funding female entrepreneurs worldwide",
    date: "Thu, Oct 15",
    time: "6:30 PM",
    host: "Hosted by Empower Her Global",
    venue: "Metropolitan Convention Center",
    gradient: "linear-gradient(135deg, #c2185b 0%, #880e4f 100%)",
    accentColor: "#f8bbd0",
    emoji: "👑",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
    description: "Keynotes from prominent female founders, micro-loan grant presentations, and networking dinner.",
    backgroundColor: "#290413",
    textColor: "#FCE4EC",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#f8bbd0",
    buttonRadius: 10,
    buttonText: "Support Her Future",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-9",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Disaster Relief Benefit Concert",
    subtitle: "Music for emergency response",
    date: "Fri, Sept 25",
    time: "8:00 PM",
    host: "Hosted by Global Red Cross",
    venue: "Civic Arena Amphitheater",
    gradient: "linear-gradient(135deg, #b71c1c 0%, #7f0000 100%)",
    accentColor: "#ff8a80",
    emoji: "🎸",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
    description: "Star-studded benefit concert bringing immediate food, shelter, and medical relief to disaster zones.",
    backgroundColor: "#260404",
    textColor: "#FFEBEE",
    titleSize: 48,
    fontWeight: "800",
    fontFamily: "Outfit",
    buttonColor: "#ff8a80",
    buttonRadius: 12,
    buttonText: "Get Benefit Ticket",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-fundraiser-10",
    type: "Fundraiser",
    category: "Fundraiser",
    title: "Tech For Good Foundation Dinner",
    subtitle: "Harnessing technology to solve hunger",
    date: "Wed, Dec 9",
    time: "7:00 PM",
    host: "Hosted by Tech Cares Alliance",
    venue: "Innovation Pavilion",
    gradient: "linear-gradient(135deg, #0288d1 0%, #01579b 100%)",
    accentColor: "#b3e5fc",
    emoji: "💻",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
    description: "Tech industry leaders gather to raise $5M for AI-driven logistics solving urban food waste.",
    backgroundColor: "#021E36",
    textColor: "#E1F5FE",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#b3e5fc",
    buttonRadius: 8,
    buttonText: "RSVP to Dinner",
    textAlignment: "center",
    gallery: [],
    sections: []
  },

  // ==================== GRADUATION (10) ====================
  {
    id: "tpl-graduation-1",
    type: "Graduation",
    category: "Graduation",
    title: "Doctorate & PhD Commencement Gala",
    subtitle: "Honoring academic excellence & research",
    date: "Fri, June 12",
    time: "6:00 PM",
    host: "Hosted by Office of the Dean",
    venue: "Grand Alumni Hall",
    gradient: "linear-gradient(135deg, #4a148c 0%, #1a237e 100%)",
    accentColor: "#ffd700",
    emoji: "🎓",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
    description: "An elegant evening celebrating years of doctoral research, dissertation defense, and academic achievement.",
    backgroundColor: "#120524",
    textColor: "#FFFDE7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#ffd700",
    buttonRadius: 10,
    buttonText: "RSVP to Gala",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-2",
    type: "Graduation",
    category: "Graduation",
    title: "High School Senior Farewell Party",
    subtitle: "Class of 2026 takes flight!",
    date: "Sat, June 6",
    time: "7:00 PM",
    host: "Hosted by Senior Class Committee",
    venue: "Sunset Beach Pavilion",
    gradient: "linear-gradient(135deg, #ff6f00 0%, #e65100 100%)",
    accentColor: "#ffe082",
    emoji: "🎉",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80",
    description: "DJ dance floor, memory slideshow wall, food trucks, and cap tossing celebration as high school ends!",
    backgroundColor: "#2B0D00",
    textColor: "#FFFDE7",
    titleSize: 48,
    fontWeight: "800",
    fontFamily: "Outfit",
    buttonColor: "#ffe082",
    buttonRadius: 12,
    buttonText: "RSVP Party",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-3",
    type: "Graduation",
    category: "Graduation",
    title: "Medical School White Coat Banquet",
    subtitle: "Doctor of Medicine Class of 2026",
    date: "Sat, May 23",
    time: "5:30 PM",
    host: "Hosted by School of Medicine",
    venue: "University Health Science Hall",
    gradient: "linear-gradient(135deg, #0277bd 0%, #01579b 100%)",
    accentColor: "#81d4fa",
    emoji: "🩺",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    description: "Celebrating the oath of medicine, white coat presentation, and new residency matching achievements.",
    backgroundColor: "#021D2E",
    textColor: "#E0F7FA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Montserrat",
    buttonColor: "#81d4fa",
    buttonRadius: 8,
    buttonText: "RSVP Banquet",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-4",
    type: "Graduation",
    category: "Graduation",
    title: "Law School Juris Doctor Gala",
    subtitle: "Upholding justice & truth",
    date: "Fri, May 29",
    time: "7:00 PM",
    host: "Hosted by School of Law Alumni",
    venue: "Justice Hall Grand Room",
    gradient: "linear-gradient(135deg, #3e2723 0%, #1b0000 100%)",
    accentColor: "#d7ccc8",
    emoji: "⚖️",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80",
    description: "An esteemed dinner honoring our Juris Doctor graduates as they prepare to take the bar examination.",
    backgroundColor: "#170D0B",
    textColor: "#EFEBE9",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#d7ccc8",
    buttonRadius: 8,
    buttonText: "Confirm Seat",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-5",
    type: "Graduation",
    category: "Graduation",
    title: "Engineering & STEM Grad Party",
    subtitle: "Building the innovations of tomorrow",
    date: "Sat, June 13",
    time: "4:00 PM",
    host: "Hosted by College of Engineering",
    venue: "Robotics Tech Loft",
    gradient: "linear-gradient(135deg, #00838f 0%, #004d40 100%)",
    accentColor: "#00e5ff",
    emoji: "⚙️",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
    description: "Showcasing capstone engineering projects, AI prototypes, and celebrating computer science degrees.",
    backgroundColor: "#031C1E",
    textColor: "#E0F7FA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#00e5ff",
    buttonRadius: 10,
    buttonText: "Join Celebration",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-6",
    type: "Graduation",
    category: "Graduation",
    title: "Arts & Design Graduate Showcase",
    subtitle: "Visualizing new horizons",
    date: "Fri, June 19",
    time: "6:30 PM",
    host: "Hosted by Academy of Fine Arts",
    venue: "Design Academy Loft Gallery",
    gradient: "linear-gradient(135deg, #37474f 0%, #212121 100%)",
    accentColor: "#ff4081",
    emoji: "🎨",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
    description: "Exhibition of senior thesis artwork, fashion design runway, film screening, and cocktail reception.",
    backgroundColor: "#161B1E",
    textColor: "#FAFAFA",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Outfit",
    buttonColor: "#ff4081",
    buttonRadius: 10,
    buttonText: "RSVP to Exhibition",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-7",
    type: "Graduation",
    category: "Graduation",
    title: "Business School MBA Celebration",
    subtitle: "Next generation of corporate leaders",
    date: "Sat, May 16",
    time: "7:00 PM",
    host: "Hosted by MBA Graduate Association",
    venue: "Executive Lounge Regency",
    gradient: "linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)",
    accentColor: "#c0ca33",
    emoji: "💼",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
    description: "An evening for MBA graduates, faculty, and industry sponsors to toast to future business triumphs.",
    backgroundColor: "#0A103D",
    textColor: "#F9FBE7",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Lora",
    buttonColor: "#c0ca33",
    buttonRadius: 8,
    buttonText: "RSVP MBA Dinner",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-8",
    type: "Graduation",
    category: "Graduation",
    title: "Kindergarten Cap & Gown Party",
    subtitle: "Little scholars big step to 1st grade!",
    date: "Fri, June 5",
    time: "10:30 AM",
    host: "Hosted by Little Scholars Academy",
    venue: "Little Scholars Auditorium",
    gradient: "linear-gradient(135deg, #fff8e1 0%, #ffe082 100%)",
    accentColor: "#f57c00",
    emoji: "🐥",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
    description: "Adorable tiny cap and gown diploma presentation, juice box toasts, and cupcake celebration!",
    backgroundColor: "#FFFDF7",
    textColor: "#3A1B00",
    titleSize: 46,
    fontWeight: "700",
    fontFamily: "Poppins",
    buttonColor: "#f57c00",
    buttonRadius: 12,
    buttonText: "RSVP Little Grad",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-9",
    type: "Graduation",
    category: "Graduation",
    title: "Nursing Graduate Pinning Ceremony",
    subtitle: "Compassion, care & healing hands",
    date: "Sat, May 30",
    time: "3:00 PM",
    host: "Hosted by College of Nursing",
    venue: "Mercy Auditorium",
    gradient: "linear-gradient(135deg, #e0f2f1 0%, #80cbc4 100%)",
    accentColor: "#00897b",
    emoji: "🩺",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    description: "Traditional nursing pin presentation, candle lighting ceremony, and reception for family and friends.",
    backgroundColor: "#F2FAF9",
    textColor: "#003630",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Inter",
    buttonColor: "#00897b",
    buttonRadius: 10,
    buttonText: "RSVP Ceremony",
    textAlignment: "center",
    gallery: [],
    sections: []
  },
  {
    id: "tpl-graduation-10",
    type: "Graduation",
    category: "Graduation",
    title: "Master's Degree Award Banquet",
    subtitle: "Mastering knowledge, leading change",
    date: "Sun, June 14",
    time: "5:00 PM",
    host: "Hosted by Graduate Student Council",
    venue: "Skyline Regency Room",
    gradient: "linear-gradient(135deg, #1b5e20 0%, #003300 100%)",
    accentColor: "#aed581",
    emoji: "📜",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
    description: "Formal dinner celebrating Master of Science and Master of Arts recipients across all departments.",
    backgroundColor: "#0B210B",
    textColor: "#F1F8E9",
    titleSize: 48,
    fontWeight: "700",
    fontFamily: "Merriweather",
    buttonColor: "#aed581",
    buttonRadius: 10,
    buttonText: "RSVP Banquet",
    textAlignment: "center",
    gallery: [],
    sections: []
  }
];

// Helper maps for effortless integration into existing components & services
export const NEW_TEMPLATES_CARD_ITEMS = NEW_TEMPLATES.map((t) => ({
  id: t.id,
  type: t.type,
  category: t.category,
  title: t.title,
  subtitle: t.subtitle,
  date: t.date,
  time: t.time,
  host: t.host,
  venue: t.venue,
  gradient: t.gradient,
  accentColor: t.accentColor,
  emoji: t.emoji,
  image: t.image,
  description: t.description,
  backgroundColor: t.backgroundColor,
  textColor: t.textColor,
  buttonColor: t.buttonColor,
  buttonText: t.buttonText,
  gallery: t.gallery,
  sections: t.sections
}));

export const NEW_TEMPLATES_CONFIG = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = {
    image: t.image,
    accentColor: t.accentColor,
    backgroundColor: t.backgroundColor,
    textColor: t.textColor,
    titleSize: t.titleSize,
    fontWeight: t.fontWeight,
    fontFamily: t.fontFamily,
    buttonColor: t.buttonColor,
    buttonRadius: t.buttonRadius,
    textAlignment: t.textAlignment,
    description: t.description
  };
  return acc;
}, {} as Record<string, any>);

export const NEW_FALLBACK_TEMPLATES = NEW_TEMPLATES.map((t) => ({
  id: t.id,
  name: `${t.title} (${t.category}) ${t.emoji}`,
  category: t.category
}));

export const NEW_TEMPLATE_IMAGES = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = t.image;
  return acc;
}, {} as Record<string, string>);

export const NEW_TEMPLATE_STYLES = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = {
    gradient: t.gradient,
    accentColor: t.accentColor,
    emoji: t.emoji,
    imageUrl: t.image,
    host: t.host,
    venue: t.venue,
    description: t.description
  };
  return acc;
}, {} as Record<string, any>);
