export interface TemplateItem {
  type: string;
  title: string;
  date: string;
  time: string;
  host: string;
  venue?: string;
  gradient: string;
  accentColor: string;
  emoji: string;
  image: string;
}

export const templateCards: TemplateItem[] = [
  {
    type: "Birthday",
    title: "Maya's 5th Birthday",
    date: "Sat, June 14",
    time: "2:00 PM",
    host: "Hosted by The Patels",
    gradient: "linear-gradient(135deg, #f9c5d1 0%, #f5a7b8 100%)",
    accentColor: "#e07090",
    emoji: "🎂",
    image: "/assets/templates/birthday.jpg",
  },
  {
    type: "Wedding",
    title: "Liam & Sofia",
    date: "Sept 21",
    time: "5:00 PM",
    host: "Together with their families",
    venue: "Vineyard Estate",
    gradient: "linear-gradient(135deg, #d4b8e8 0%, #b8a0d4 100%)",
    accentColor: "#9070c0",
    emoji: "💍",
    image: "/assets/templates/wedding.jpg",
  },
  {
    type: "Corporate",
    title: "Annual Product Launch",
    date: "Oct 3",
    time: "6:30 PM",
    host: "Northwind Technologies",
    venue: "The Innovation Hub",
    gradient: "linear-gradient(135deg, #a8c8e8 0%, #80a8d0 100%)",
    accentColor: "#4080b0",
    emoji: "🚀",
    image: "/assets/templates/corporate.jpg",
  },
  {
    type: "Dinner Party",
    title: "Supper Club No. 7",
    date: "Fri, May 30",
    time: "7:30 PM",
    host: "Hosted by Chef Amara",
    gradient: "linear-gradient(135deg, #d4c8a0 0%, #c0b080 100%)",
    accentColor: "#907030",
    emoji: "🍽️",
    image: "/assets/templates/dinner.jpg",
  },
  {
    type: "Baby Shower",
    title: "A Little One is Coming",
    date: "Aug 9",
    time: "12:00 PM",
    host: "Celebrating Baby Reyes",
    venue: "Garden Terrace",
    gradient: "linear-gradient(135deg, #c8e8c8 0%, #a8d0a8 100%)",
    accentColor: "#4a9a4a",
    emoji: "🍼",
    image: "/assets/templates/babyshower.jpg",
  },
  {
    type: "Charity Gala",
    title: "Bright Futures Gala",
    date: "Nov 15",
    time: "8:00 PM",
    host: "Bright Futures Foundation",
    venue: "Grand Ballroom",
    gradient: "linear-gradient(135deg, #c9a84c 0%, #a07820 100%)",
    accentColor: "#a07820",
    emoji: "✨",
    image: "/assets/templates/gala.jpg",
  },
  {
    type: "Live Music",
    title: "Rooftop Sessions",
    date: "July 12",
    time: "9:00 PM",
    host: "Presented by Echo Collective",
    venue: "Skyline Loft",
    gradient: "linear-gradient(135deg, #2D1B3D 0%, #4a2a6a 100%)",
    accentColor: "#9970d0",
    emoji: "🎵",
    image: "/assets/templates/music.jpg",
  },
  {
    type: "Anniversary",
    title: "25 Years Together",
    date: "Dec 6",
    time: "6:00 PM",
    host: "Celebrating James & Elena",
    venue: "Lakeside Manor",
    gradient: "linear-gradient(135deg, #e8c4b8 0%, #d0a090 100%)",
    accentColor: "#c06840",
    emoji: "🥂",
    image: "/assets/templates/anniversary.jpg",
  },
  {
    type: "Graduation",
    title: "Graduation Gala",
    date: "Fri, June 19",
    time: "7:00 PM",
    host: "Hosted by The Office of the Dean",
    venue: "University Grand Hall",
    gradient: "linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)",
    accentColor: "#d4af37",
    emoji: "🎓",
    image: "/assets/templates/graduation_gala.jpg",
  },
  {
    type: "Community",
    title: "Community Meetup",
    date: "Sat, May 16",
    time: "3:00 PM",
    host: "Oakwood Neighborhood",
    venue: "Oakwood Community Park",
    gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
    accentColor: "#11998e",
    emoji: "🏡",
    image: "/assets/templates/community_meetup.jpg",
  },
  {
    type: "Networking",
    title: "Professional Networking",
    date: "Thu, Oct 15",
    time: "6:30 PM",
    host: "Metro Business Alliance",
    venue: "The Summit Boardroom",
    gradient: "linear-gradient(135deg, #2b5876 0%, #4e4376 100%)",
    accentColor: "#6f86d6",
    emoji: "🤝",
    image: "/assets/templates/networking_professional.jpg",
  },
];
