// =============================================================================
// Premium Designer Suite Templates Registry
// These 6 premium templates are part of the unified template dataset rendered by
// the "Choose from editable templates" tab (dashboard + home hero widget).
// The `source` marker below keeps them out of the curated home page
// "Invitations your guests will love" carousel.
// =============================================================================

import type { EviteTemplateSchema } from "./newTemplatesData";

export interface HomeTemplateItem extends EviteTemplateSchema {
  tier: "premium";
  source: "home-gallery-only";
  backgroundSurface: string;
  envelopeDesign: {
    outerColor: string;
    flapColor: string;
    liner: string;
    linerCss?: string;
    linerColor?: string;
    description: string;
  };
  cardStyle: {
    description: string;
    frameSvg: string;
    illustrationSvg?: string;
  };
  defaultEventDetails: {
    host: string;
    dateTime: string;
    venue: string;
    description?: string;
  };
}

export const homeTemplatesData: HomeTemplateItem[] = [
  // 1. Ribbons, Bows
  {
    id: "ribbons-bows",
    title: "Ribbons, Bows",
    name: "Ribbons, Bows",
    tier: "premium",
    isPremium: true,
    badge: "Premium",
    category: "Bridal Shower",
    source: "home-gallery-only",
    tags: ["home-gallery-only", "premium", "bridal shower", "bow", "minimalist"],
    backgroundSurface: "Soft ivory lace texture overlay.",
    mockupUrl: "/assets/templates/ribbons-bows-mockup.svg",
    thumbnailUrl: "/assets/templates/ribbons-bows-mockup.svg",
    envelopeColor: "#18181B",
    linerColor: "#FFFFFF",
    envelopeLiner: "/templates/envelopes/ribbons-bows-liner.svg",
    envelopeDesign: {
      outerColor: "#18181B",
      flapColor: "#18181B",
      liner: "/templates/envelopes/ribbons-bows-liner.svg",
      linerCss: "url('/templates/envelopes/ribbons-bows-liner.svg') center / cover no-repeat",
      linerColor: "#FFFFFF",
      description: "Sharp black-and-white striped/floral patterned inner liner with a bold black envelope pocket.",
    },
    cardStyle: {
      description: "Minimalist card featuring a bold, realistic hanging black silk ribbon bow graphic with high-contrast editorial serif text.",
      frameSvg: "/assets/templates/ribbons-bows-bg.svg",
      illustrationSvg: "/assets/templates/illustrations/black-silk-bow.svg",
    },
    defaultEventDetails: {
      host: "Danielle Johnson",
      dateTime: "May 18 at 12 PM",
      venue: "14 Meadow Drive",
      description: "Bridal Shower celebrating Danielle Johnson | May 18 at 12 PM | Meadow Drive",
    },
    backdrop: {
      type: "texture",
      value: "/assets/backdrops/soft-ivory-lace.svg",
      color: "#F8F5EE",
      gradient: "url('/assets/backdrops/soft-ivory-lace.svg') center / cover no-repeat",
    },
    envelope: {
      outerColor: "#18181B",
      flapColor: "#18181B",
      linerPatternUrl: "/templates/envelopes/ribbons-bows-liner.svg",
      innerLiner: "/templates/envelopes/ribbons-bows-liner.svg",
      linerCss: "url('/templates/envelopes/ribbons-bows-liner.svg') center / cover no-repeat",
      linerColor: "#FFFFFF",
      flapStyle: "triangle",
      isOpen: true,
      isOpenUpward: true,
      shadowColor: "rgba(0,0,0,0.3)",
    },
    card: {
      backgroundColor: "#FFFFFF",
      safeArea: { top: "20%", bottom: "16%", left: "15%", right: "35%" },
      borderIllustration: "/assets/templates/ribbons-bows-bg.svg",
      artworkUrl: "/assets/templates/ribbons-bows-bg.svg",
      decorativeBorderSvgUrl: "/assets/templates/ribbons-bows-bg.svg",
      aspectRatio: "5x7",
      cssConfig: {
        backgroundColor: "#FFFFFF",
        borderRadius: "8px",
        paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.22)",
      },
    },
    innerCardLayer: {
      backgroundColor: "#FFFFFF",
      borderRadius: "8px",
      paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.22)",
      aspectRatio: "5/7",
    },
    defaultTextBlocks: [
      {
        id: "header",
        text: "join us for a",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 14,
        fontStyle: "italic",
        color: "#555555",
        align: "left",
        position: { top: "25%", left: "30%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "title",
        text: "Bridal\nShower",
        fontFamily: "Great Vibes, cursive",
        fontSize: 38,
        lineHeight: 1.1,
        color: "#18181B",
        align: "left",
        position: { top: "36%", left: "33%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "subtitle",
        text: "celebrating",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 13,
        fontStyle: "italic",
        color: "#555555",
        align: "left",
        position: { top: "48%", left: "30%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "guest-name",
        text: "DANIELLE\nJOHNSON",
        fontFamily: "Playfair Display, Cinzel, serif",
        fontSize: 20,
        fontWeight: "700",
        letterSpacing: "2.5px",
        lineHeight: 1.25,
        color: "#18181B",
        align: "left",
        position: { top: "60%", left: "33%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "datetime",
        text: "MAY 18 AT 12 PM\n14 MEADOW DRIVE",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        fontWeight: "600",
        letterSpacing: "1.5px",
        lineHeight: 1.6,
        color: "#333333",
        align: "left",
        position: { top: "76%", left: "35%", transform: "translate(-50%, -50%)" },
      },
    ],
    defaultTextLayers: [
      {
        id: "header",
        key: "header",
        text: "join us for a",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 14,
        fontStyle: "italic",
        color: "#555555",
        fontWeight: "400",
        textAlign: "left",
        top: 25,
        left: 30,
      },
      {
        id: "title",
        key: "title",
        text: "Bridal\nShower",
        fontFamily: "Great Vibes, cursive",
        fontSize: 38,
        lineHeight: 1.1,
        color: "#18181B",
        fontWeight: "400",
        textAlign: "left",
        top: 36,
        left: 33,
      },
      {
        id: "subtitle",
        key: "subtitle",
        text: "celebrating",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 13,
        fontStyle: "italic",
        color: "#555555",
        fontWeight: "400",
        textAlign: "left",
        top: 48,
        left: 30,
      },
      {
        id: "guest-name",
        key: "guest",
        text: "DANIELLE\nJOHNSON",
        fontFamily: "Playfair Display, Cinzel, serif",
        fontSize: 20,
        fontWeight: "700",
        letterSpacing: "2.5px",
        lineHeight: 1.25,
        color: "#18181B",
        textAlign: "left",
        top: 60,
        left: 33,
      },
      {
        id: "datetime",
        key: "datetime",
        text: "MAY 18 AT 12 PM\n14 MEADOW DRIVE",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        fontWeight: "600",
        letterSpacing: "1.5px",
        lineHeight: 1.6,
        color: "#333333",
        textAlign: "left",
        top: 76,
        left: 35,
      },
    ],
  },

  // 2. Painted Petals
  {
    id: "painted-petals",
    title: "Painted Petals",
    name: "Painted Petals",
    tier: "premium",
    isPremium: true,
    badge: "Premium",
    category: "Shower & Florals",
    source: "home-gallery-only",
    tags: ["home-gallery-only", "premium", "shower", "florals", "watercolor", "cornflowers"],
    backgroundSurface: "Textured debossed white floral paper relief.",
    mockupUrl: "/assets/templates/painted-petals-mockup.svg",
    thumbnailUrl: "/assets/templates/painted-petals-mockup.svg",
    envelopeColor: "#10357A",
    linerColor: "#0E2E6B",
    envelopeLiner: "linear-gradient(135deg, #1A4494 0%, #0E2E6B 100%)",
    envelopeDesign: {
      outerColor: "#10357A",
      flapColor: "#143D8A",
      liner: "linear-gradient(135deg, #1A4494 0%, #0E2E6B 100%)",
      linerCss: "linear-gradient(135deg, #1A4494 0%, #0E2E6B 100%)",
      linerColor: "#0E2E6B",
      description: "Royal cobalt blue envelope flap with crisp clean creases.",
    },
    cardStyle: {
      description: "Soft watercolor cornflowers and wildflowers framing elegant cursive blue script typography.",
      frameSvg: "/assets/templates/painted-petals-bg.svg",
      illustrationSvg: "/assets/templates/illustrations/cornflowers-wildflowers.svg",
    },
    defaultEventDetails: {
      host: "Emilia Hernandez",
      dateTime: "Sunday, June 17 at 1 PM",
      venue: "High Noon Farm",
      description: "Join us to shower Emilia Hernandez | Sunday, June 17 at 1 PM | High Noon Farm",
    },
    backdrop: {
      type: "texture",
      value: "/assets/backdrops/white-debossed-floral.svg",
      color: "#F8F8F8",
      gradient: "url('/assets/backdrops/white-debossed-floral.svg') center / cover no-repeat",
    },
    envelope: {
      outerColor: "#10357A",
      flapColor: "#143D8A",
      linerPatternUrl: "",
      innerLiner: "linear-gradient(135deg, #1A4494 0%, #0E2E6B 100%)",
      linerCss: "linear-gradient(135deg, #1A4494 0%, #0E2E6B 100%)",
      linerColor: "#0E2E6B",
      flapStyle: "triangle",
      isOpen: true,
      isOpenUpward: true,
      shadowColor: "rgba(0,0,0,0.25)",
    },
    card: {
      backgroundColor: "#FFFDF8",
      safeArea: { top: "18%", bottom: "16%", left: "18%", right: "18%" },
      borderIllustration: "/assets/templates/painted-petals-bg.svg",
      artworkUrl: "/assets/templates/painted-petals-bg.svg",
      decorativeBorderSvgUrl: "/assets/templates/painted-petals-bg.svg",
      aspectRatio: "5x7",
      cssConfig: {
        backgroundColor: "#FFFDF8",
        borderRadius: "10px",
        paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.22)",
      },
    },
    innerCardLayer: {
      backgroundColor: "#FFFDF8",
      borderRadius: "10px",
      paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.22)",
      aspectRatio: "5/7",
    },
    defaultTextBlocks: [
      {
        id: "header",
        text: "JOIN US TO SHOWER",
        fontFamily: "Cinzel, Cormorant Garamond, serif",
        fontSize: 12,
        letterSpacing: "2.5px",
        color: "#1B3E75",
        align: "center",
        position: { top: "28%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "title-name",
        text: "Emilia Hernandez",
        fontFamily: "Great Vibes, cursive",
        fontSize: 40,
        lineHeight: 1.15,
        color: "#10357A",
        align: "center",
        position: { top: "44%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "datetime",
        text: "SUNDAY, JUNE 17 AT 1 PM",
        fontFamily: "Cormorant Garamond, serif",
        fontSize: 13,
        letterSpacing: "1.5px",
        color: "#2A4D80",
        align: "center",
        position: { top: "60%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "venue",
        text: "HIGH NOON FARM",
        fontFamily: "Cormorant Garamond, serif",
        fontSize: 13,
        letterSpacing: "2px",
        color: "#2A4D80",
        align: "center",
        position: { top: "68%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "rsvp",
        text: "RSVP DETAILS BELOW",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 9.5,
        letterSpacing: "1.5px",
        color: "#5C769D",
        align: "center",
        position: { top: "78%", left: "50%", transform: "translate(-50%, -50%)" },
      },
    ],
    defaultTextLayers: [
      {
        id: "header",
        key: "header",
        text: "JOIN US TO SHOWER",
        fontFamily: "Cinzel, Cormorant Garamond, serif",
        fontSize: 12,
        letterSpacing: "2.5px",
        color: "#1B3E75",
        fontWeight: "600",
        textAlign: "center",
        top: 28,
        left: 50,
      },
      {
        id: "title-name",
        key: "title",
        text: "Emilia Hernandez",
        fontFamily: "Great Vibes, cursive",
        fontSize: 40,
        lineHeight: 1.15,
        color: "#10357A",
        fontWeight: "400",
        textAlign: "center",
        top: 44,
        left: 50,
      },
      {
        id: "datetime",
        key: "datetime",
        text: "SUNDAY, JUNE 17 AT 1 PM",
        fontFamily: "Cormorant Garamond, serif",
        fontSize: 13,
        letterSpacing: "1.5px",
        color: "#2A4D80",
        fontWeight: "600",
        textAlign: "center",
        top: 60,
        left: 50,
      },
      {
        id: "venue",
        key: "venue",
        text: "HIGH NOON FARM",
        fontFamily: "Cormorant Garamond, serif",
        fontSize: 13,
        letterSpacing: "2px",
        color: "#2A4D80",
        fontWeight: "600",
        textAlign: "center",
        top: 68,
        left: 50,
      },
      {
        id: "rsvp",
        key: "rsvp",
        text: "RSVP DETAILS BELOW",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 9.5,
        letterSpacing: "1.5px",
        color: "#5C769D",
        fontWeight: "500",
        textAlign: "center",
        top: 78,
        left: 50,
      },
    ],
  },

  // 3. Lemons & Blossoms
  {
    id: "lemons-blossoms",
    title: "Lemons & Blossoms",
    name: "Lemons & Blossoms",
    tier: "premium",
    isPremium: true,
    badge: "Premium",
    category: "Bridal Shower",
    source: "home-gallery-only",
    tags: ["home-gallery-only", "premium", "bridal shower", "lemon", "amalfi", "mediterranean"],
    backgroundSurface: "Subtle linen cloth texture.",
    mockupUrl: "/assets/templates/lemons-blossoms-mockup.svg",
    thumbnailUrl: "/assets/templates/lemons-blossoms-mockup.svg",
    envelopeColor: "#FAD02C",
    linerColor: "#FFF176",
    envelopeLiner: "/templates/envelopes/lemons-blossoms-liner.svg",
    envelopeDesign: {
      outerColor: "#FAD02C",
      flapColor: "#FFE57F",
      liner: "/templates/envelopes/lemons-blossoms-liner.svg",
      linerCss: "url('/templates/envelopes/lemons-blossoms-liner.svg') center / cover no-repeat",
      linerColor: "#FFF176",
      description: "Pastel lemon-yellow striped envelope lining and outer flap.",
    },
    cardStyle: {
      description: "Amalfi coast lemon tree branches with white blossoms framing an arched Mediterranean title card.",
      frameSvg: "/assets/templates/lemons-blossoms-bg.svg",
      illustrationSvg: "/assets/templates/illustrations/amalfi-lemons.svg",
    },
    defaultEventDetails: {
      host: "Taylor Johnson",
      dateTime: "Sunday, August 14 at 2 PM",
      venue: "The Garden Estate",
      description: "La Dolce Vita - Please join us to shower Taylor Johnson | Sunday, August 14 at 2 PM | The Garden Estate",
    },
    backdrop: {
      type: "texture",
      value: "/assets/backdrops/subtle-linen-cloth.svg",
      color: "#F4EFEA",
      gradient: "url('/assets/backdrops/subtle-linen-cloth.svg') center / cover no-repeat",
    },
    envelope: {
      outerColor: "#FAD02C",
      flapColor: "#FFE57F",
      linerPatternUrl: "/templates/envelopes/lemons-blossoms-liner.svg",
      innerLiner: "/templates/envelopes/lemons-blossoms-liner.svg",
      linerCss: "url('/templates/envelopes/lemons-blossoms-liner.svg') center / cover no-repeat",
      linerColor: "#FFF176",
      flapStyle: "triangle",
      isOpen: true,
      isOpenUpward: true,
      shadowColor: "rgba(0,0,0,0.22)",
    },
    card: {
      backgroundColor: "#FFFFFF",
      safeArea: { top: "18%", bottom: "16%", left: "20%", right: "20%" },
      borderIllustration: "/assets/templates/lemons-blossoms-bg.svg",
      artworkUrl: "/assets/templates/lemons-blossoms-bg.svg",
      decorativeBorderSvgUrl: "/assets/templates/lemons-blossoms-bg.svg",
      aspectRatio: "5x7",
      cssConfig: {
        backgroundColor: "#FFFFFF",
        borderRadius: "140px 140px 14px 14px",
        paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.24)",
      },
    },
    innerCardLayer: {
      backgroundColor: "#FFFFFF",
      borderRadius: "140px 140px 14px 14px",
      paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.24)",
      aspectRatio: "5/7",
    },
    defaultTextBlocks: [
      {
        id: "title",
        text: "La Dolce\nVita",
        fontFamily: "Parisienne, Great Vibes, cursive",
        fontSize: 36,
        lineHeight: 1.15,
        color: "#264653",
        align: "center",
        position: { top: "32%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "header",
        text: "PLEASE JOIN US TO SHOWER",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 10.5,
        letterSpacing: "2px",
        color: "#2A6F97",
        align: "center",
        position: { top: "48%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "title-name",
        text: "TAYLOR JOHNSON",
        fontFamily: "Playfair Display, serif",
        fontSize: 18,
        fontWeight: "700",
        letterSpacing: "2px",
        color: "#1D3557",
        align: "center",
        position: { top: "56%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "datetime",
        text: "SUNDAY, AUGUST 14 AT 2 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "1.5px",
        color: "#457B9D",
        align: "center",
        position: { top: "66%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "venue",
        text: "THE GARDEN ESTATE",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "2px",
        color: "#457B9D",
        align: "center",
        position: { top: "72%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "rsvp",
        text: "for registry details below",
        fontFamily: "Great Vibes, cursive",
        fontSize: 18,
        color: "#6C757D",
        align: "center",
        position: { top: "82%", left: "50%", transform: "translate(-50%, -50%)" },
      },
    ],
    defaultTextLayers: [
      {
        id: "title",
        key: "title",
        text: "La Dolce\nVita",
        fontFamily: "Parisienne, Great Vibes, cursive",
        fontSize: 36,
        lineHeight: 1.15,
        color: "#264653",
        fontWeight: "400",
        textAlign: "center",
        top: 32,
        left: 50,
      },
      {
        id: "header",
        key: "header",
        text: "PLEASE JOIN US TO SHOWER",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 10.5,
        letterSpacing: "2px",
        color: "#2A6F97",
        fontWeight: "600",
        textAlign: "center",
        top: 48,
        left: 50,
      },
      {
        id: "title-name",
        key: "guest",
        text: "TAYLOR JOHNSON",
        fontFamily: "Playfair Display, serif",
        fontSize: 18,
        fontWeight: "700",
        letterSpacing: "2px",
        color: "#1D3557",
        textAlign: "center",
        top: 56,
        left: 50,
      },
      {
        id: "datetime",
        key: "datetime",
        text: "SUNDAY, AUGUST 14 AT 2 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "1.5px",
        color: "#457B9D",
        fontWeight: "600",
        textAlign: "center",
        top: 66,
        left: 50,
      },
      {
        id: "venue",
        key: "venue",
        text: "THE GARDEN ESTATE",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "2px",
        color: "#457B9D",
        fontWeight: "600",
        textAlign: "center",
        top: 72,
        left: 50,
      },
      {
        id: "rsvp",
        key: "rsvp",
        text: "for registry details below",
        fontFamily: "Great Vibes, cursive",
        fontSize: 18,
        color: "#6C757D",
        fontWeight: "400",
        textAlign: "center",
        top: 82,
        left: 50,
      },
    ],
  },

  // 4. Mamma Mia
  {
    id: "mamma-mia",
    title: "Mamma Mia",
    name: "Mamma Mia",
    tier: "premium",
    isPremium: true,
    badge: "Premium",
    category: "Bridal Shower & Italian",
    source: "home-gallery-only",
    tags: ["home-gallery-only", "premium", "bridal shower", "italian", "majolica"],
    backgroundSurface: "Natural rustic burlap/linen fabric texture.",
    mockupUrl: "/assets/templates/mamma-mia-mockup.svg",
    thumbnailUrl: "/assets/templates/mamma-mia-mockup.svg",
    envelopeColor: "#0A192F",
    linerColor: "#1E3A5F",
    envelopeLiner: "linear-gradient(135deg, #152238 0%, #1E3A5F 100%)",
    envelopeDesign: {
      outerColor: "#0A192F",
      flapColor: "#112240",
      liner: "linear-gradient(135deg, #152238 0%, #1E3A5F 100%)",
      linerCss: "linear-gradient(135deg, #152238 0%, #1E3A5F 100%)",
      linerColor: "#1E3A5F",
      description: "Deep Mediterranean royal navy blue envelope.",
    },
    cardStyle: {
      description: "Blue-and-white Majolica ceramic tile border accented with fresh ripe lemons and olive greenery.",
      frameSvg: "/assets/templates/mamma-mia-bg.svg",
      illustrationSvg: "/assets/templates/illustrations/majolica-lemons.svg",
    },
    defaultEventDetails: {
      host: "Lauren Sanders",
      dateTime: "Saturday, July 20th at 1:30 PM",
      venue: "Villa Bella",
      description: "Join us for a bridal shower honoring bride-to-be Lauren Sanders | Saturday, July 20th at 1:30 PM | Villa Bella",
    },
    backdrop: {
      type: "texture",
      value: "/assets/backdrops/rustic-burlap-linen.svg",
      color: "#DFD6C4",
      gradient: "url('/assets/backdrops/rustic-burlap-linen.svg') center / cover no-repeat",
    },
    envelope: {
      outerColor: "#0A192F",
      flapColor: "#112240",
      linerPatternUrl: "",
      innerLiner: "linear-gradient(135deg, #152238 0%, #1E3A5F 100%)",
      linerCss: "linear-gradient(135deg, #152238 0%, #1E3A5F 100%)",
      linerColor: "#1E3A5F",
      flapStyle: "triangle",
      isOpen: true,
      isOpenUpward: true,
      shadowColor: "rgba(0,0,0,0.35)",
    },
    card: {
      backgroundColor: "#FFFFFF",
      safeArea: { top: "18%", bottom: "16%", left: "18%", right: "18%" },
      borderIllustration: "/assets/templates/mamma-mia-bg.svg",
      artworkUrl: "/assets/templates/mamma-mia-bg.svg",
      decorativeBorderSvgUrl: "/assets/templates/mamma-mia-bg.svg",
      aspectRatio: "5x7",
      cssConfig: {
        backgroundColor: "#FFFFFF",
        borderRadius: "14px",
        paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.28)",
      },
    },
    innerCardLayer: {
      backgroundColor: "#FFFFFF",
      borderRadius: "14px",
      paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.28)",
      aspectRatio: "5/7",
    },
    defaultTextBlocks: [
      {
        id: "header",
        text: "join us for a bridal shower\nhonoring bride-to-be",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 13,
        fontStyle: "italic",
        lineHeight: 1.4,
        color: "#1D3557",
        align: "center",
        position: { top: "26%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "title-name",
        text: "Lauren Sanders",
        fontFamily: "Great Vibes, cursive",
        fontSize: 42,
        lineHeight: 1.15,
        color: "#1565C0",
        align: "center",
        position: { top: "44%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "datetime",
        text: "Saturday, July 20th at 1:30 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 12,
        fontWeight: "600",
        color: "#1E3A5F",
        align: "center",
        position: { top: "62%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "venue",
        text: "Villa Bella\n10 Piazza Veneto Dallas",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        lineHeight: 1.5,
        color: "#415A77",
        align: "center",
        position: { top: "74%", left: "50%", transform: "translate(-50%, -50%)" },
      },
    ],
    defaultTextLayers: [
      {
        id: "header",
        key: "header",
        text: "join us for a bridal shower\nhonoring bride-to-be",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 13,
        fontStyle: "italic",
        lineHeight: 1.4,
        color: "#1D3557",
        fontWeight: "400",
        textAlign: "center",
        top: 26,
        left: 50,
      },
      {
        id: "title-name",
        key: "title",
        text: "Lauren Sanders",
        fontFamily: "Great Vibes, cursive",
        fontSize: 42,
        lineHeight: 1.15,
        color: "#1565C0",
        fontWeight: "400",
        textAlign: "center",
        top: 44,
        left: 50,
      },
      {
        id: "datetime",
        key: "datetime",
        text: "Saturday, July 20th at 1:30 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 12,
        fontWeight: "600",
        color: "#1E3A5F",
        textAlign: "center",
        top: 62,
        left: 50,
      },
      {
        id: "venue",
        key: "venue",
        text: "Villa Bella\n10 Piazza Veneto Dallas",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        lineHeight: 1.5,
        color: "#415A77",
        fontWeight: "500",
        textAlign: "center",
        top: 74,
        left: 50,
      },
    ],
  },

  // 5. Moonlit Grove
  {
    id: "moonlit-grove",
    title: "Moonlit Grove",
    name: "Moonlit Grove",
    tier: "premium",
    isPremium: true,
    badge: "Premium",
    category: "Baby Shower & Birthday",
    source: "home-gallery-only",
    tags: ["home-gallery-only", "premium", "baby shower", "woodland", "moonlit", "fairy tale"],
    backgroundSurface: "Dark polished horizontal wooden plank backdrop.",
    mockupUrl: "/assets/templates/moonlit-grove-mockup.svg",
    thumbnailUrl: "/assets/templates/moonlit-grove-mockup.svg",
    envelopeColor: "#C4A482",
    linerColor: "#D7C4B7",
    envelopeLiner: "/templates/envelopes/woodland-gingham-liner.svg",
    envelopeDesign: {
      outerColor: "#C4A482",
      flapColor: "#D3B89B",
      liner: "/templates/envelopes/woodland-gingham-liner.svg",
      linerCss: "url('/templates/envelopes/woodland-gingham-liner.svg') center / cover no-repeat",
      linerColor: "#D7C4B7",
      description: "Neutral kraft paper envelope lined with a light woodland gingham check pattern.",
    },
    cardStyle: {
      description: "Dark forest green/teal card with gold foil moon, whimsical woodland creatures (owl, squirrels, mushrooms), and fairy-tale serif typography.",
      frameSvg: "/assets/templates/moonlit-grove-bg.svg",
      illustrationSvg: "/assets/templates/illustrations/woodland-creatures.svg",
    },
    defaultEventDetails: {
      host: "Dani Johnson",
      dateTime: "October 14th at 2 PM",
      venue: "Pine Ridge",
      description: "The Sweetest Chapter - Shower for Dani Johnson | October 14th at 2 PM | Pine Ridge",
    },
    backdrop: {
      type: "texture",
      value: "/assets/backdrops/dark-wood-planks.svg",
      color: "#2A1B12",
      gradient: "url('/assets/backdrops/dark-wood-planks.svg') center / cover no-repeat",
    },
    envelope: {
      outerColor: "#C4A482",
      flapColor: "#D3B89B",
      linerPatternUrl: "/templates/envelopes/woodland-gingham-liner.svg",
      innerLiner: "/templates/envelopes/woodland-gingham-liner.svg",
      linerCss: "url('/templates/envelopes/woodland-gingham-liner.svg') center / cover no-repeat",
      linerColor: "#D7C4B7",
      flapStyle: "triangle",
      isOpen: true,
      isOpenUpward: true,
      shadowColor: "rgba(0,0,0,0.38)",
    },
    card: {
      backgroundColor: "#0B2726",
      safeArea: { top: "25%", bottom: "24%", left: "16%", right: "16%" },
      borderIllustration: "/assets/templates/moonlit-grove-bg.svg",
      artworkUrl: "/assets/templates/moonlit-grove-bg.svg",
      decorativeBorderSvgUrl: "/assets/templates/moonlit-grove-bg.svg",
      aspectRatio: "5x7",
      cssConfig: {
        backgroundColor: "#0B2726",
        borderRadius: "14px",
        paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.38)",
      },
    },
    innerCardLayer: {
      backgroundColor: "#0B2726",
      borderRadius: "14px",
      paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.38)",
      aspectRatio: "5/7",
    },
    defaultTextBlocks: [
      {
        id: "title",
        text: "The Sweetest Chapter",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 26,
        fontWeight: "700",
        fontStyle: "italic",
        lineHeight: 1.25,
        color: "#F5E6CA",
        align: "center",
        position: { top: "36%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "header",
        text: "BABY SHOWER HONORING",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 10,
        letterSpacing: "2px",
        color: "#C2B08B",
        align: "center",
        position: { top: "48%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "title-name",
        text: "DANI JOHNSON",
        fontFamily: "Cinzel, Playfair Display, serif",
        fontSize: 18,
        fontWeight: "700",
        letterSpacing: "2px",
        color: "#F5E6CA",
        align: "center",
        position: { top: "56%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "datetime",
        text: "OCTOBER 14TH AT 2 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "1.5px",
        color: "#C2B08B",
        align: "center",
        position: { top: "66%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "venue",
        text: "PINE RIDGE",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "2px",
        color: "#C2B08B",
        align: "center",
        position: { top: "72%", left: "50%", transform: "translate(-50%, -50%)" },
      },
    ],
    defaultTextLayers: [
      {
        id: "title",
        key: "title",
        text: "The Sweetest Chapter",
        fontFamily: "Playfair Display, Georgia, serif",
        fontSize: 26,
        fontWeight: "700",
        fontStyle: "italic",
        lineHeight: 1.25,
        color: "#F5E6CA",
        textAlign: "center",
        top: 36,
        left: 50,
      },
      {
        id: "header",
        key: "header",
        text: "BABY SHOWER HONORING",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 10,
        letterSpacing: "2px",
        color: "#C2B08B",
        fontWeight: "600",
        textAlign: "center",
        top: 48,
        left: 50,
      },
      {
        id: "title-name",
        key: "guest",
        text: "DANI JOHNSON",
        fontFamily: "Cinzel, Playfair Display, serif",
        fontSize: 18,
        fontWeight: "700",
        letterSpacing: "2px",
        color: "#F5E6CA",
        textAlign: "center",
        top: 56,
        left: 50,
      },
      {
        id: "datetime",
        key: "datetime",
        text: "OCTOBER 14TH AT 2 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "1.5px",
        color: "#C2B08B",
        fontWeight: "600",
        textAlign: "center",
        top: 66,
        left: 50,
      },
      {
        id: "venue",
        key: "venue",
        text: "PINE RIDGE",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "2px",
        color: "#C2B08B",
        fontWeight: "600",
        textAlign: "center",
        top: 72,
        left: 50,
      },
    ],
  },

  // 6. Taste Of Italy
  {
    id: "taste-of-italy",
    title: "Taste Of Italy",
    name: "Taste Of Italy",
    tier: "premium",
    isPremium: true,
    badge: "Premium",
    category: "Rehearsal Dinner & Party",
    source: "home-gallery-only",
    tags: ["home-gallery-only", "premium", "rehearsal dinner", "italian", "trattoria"],
    backgroundSurface: "Sage green and white vertical Italian bistro stripes.",
    mockupUrl: "/assets/templates/taste-of-italy-mockup.svg",
    thumbnailUrl: "/assets/templates/taste-of-italy-mockup.svg",
    envelopeColor: "#C92A2A",
    linerColor: "#D63031",
    envelopeLiner: "linear-gradient(135deg, #D63031 0%, #A61E1E 100%)",
    envelopeDesign: {
      outerColor: "#C92A2A",
      flapColor: "#E03131",
      liner: "linear-gradient(135deg, #D63031 0%, #A61E1E 100%)",
      linerCss: "linear-gradient(135deg, #D63031 0%, #A61E1E 100%)",
      linerColor: "#D63031",
      description: "Vibrant tomato-red open envelope flap.",
    },
    cardStyle: {
      description: "Red-and-white checkered trattoria border with hand-drawn Italian graphics (wine bottle, pasta, tomatoes, olive sprigs) and playful script typography.",
      frameSvg: "/assets/templates/taste-of-italy-bg.svg",
      illustrationSvg: "/assets/templates/illustrations/italian-trattoria.svg",
    },
    defaultEventDetails: {
      host: "Mallory Evans",
      dateTime: "August 24th at 7 PM",
      venue: "Little Italy Trattoria",
      description: "That's Amore! Mallory Evans | August 24th at 7 PM | Little Italy Trattoria",
    },
    backdrop: {
      type: "texture",
      value: "/assets/backdrops/sage-bistro-stripes.svg",
      color: "#F4EFE6",
      gradient: "url('/assets/backdrops/sage-bistro-stripes.svg') center / cover no-repeat",
    },
    envelope: {
      outerColor: "#C92A2A",
      flapColor: "#E03131",
      linerPatternUrl: "",
      innerLiner: "linear-gradient(135deg, #D63031 0%, #A61E1E 100%)",
      linerCss: "linear-gradient(135deg, #D63031 0%, #A61E1E 100%)",
      linerColor: "#D63031",
      flapStyle: "triangle",
      isOpen: true,
      isOpenUpward: true,
      shadowColor: "rgba(0,0,0,0.25)",
    },
    card: {
      backgroundColor: "#FFFDF9",
      safeArea: { top: "18%", bottom: "25%", left: "18%", right: "18%" },
      borderIllustration: "/assets/templates/taste-of-italy-bg.svg",
      artworkUrl: "/assets/templates/taste-of-italy-bg.svg",
      decorativeBorderSvgUrl: "/assets/templates/taste-of-italy-bg.svg",
      aspectRatio: "5x7",
      cssConfig: {
        backgroundColor: "#FFFDF9",
        borderRadius: "14px",
        paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.22)",
      },
    },
    innerCardLayer: {
      backgroundColor: "#FFFDF9",
      borderRadius: "14px",
      paperShadow: "0 14px 30px -6px rgba(0, 0, 0, 0.22)",
      aspectRatio: "5/7",
    },
    defaultTextBlocks: [
      {
        id: "title",
        text: "That's amore",
        fontFamily: "Pacifico, Caveat, cursive",
        fontSize: 36,
        color: "#2E5A27",
        align: "center",
        position: { top: "25%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "header",
        text: "A REHEARSAL DINNER HONORING",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 9.5,
        letterSpacing: "1.5px",
        color: "#8B0000",
        align: "center",
        position: { top: "36%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "title-name",
        text: "Mallory Evans",
        fontFamily: "Playfair Display, serif",
        fontSize: 26,
        fontWeight: "700",
        color: "#1C1917",
        align: "center",
        position: { top: "45%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "datetime",
        text: "AUGUST 24TH AT 7 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "1.5px",
        color: "#57534E",
        align: "center",
        position: { top: "56%", left: "50%", transform: "translate(-50%, -50%)" },
      },
      {
        id: "venue",
        text: "LITTLE ITALY TRATTORIA",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "2px",
        color: "#78716C",
        align: "center",
        position: { top: "63%", left: "50%", transform: "translate(-50%, -50%)" },
      },
    ],
    defaultTextLayers: [
      {
        id: "title",
        key: "title",
        text: "That's amore",
        fontFamily: "Pacifico, Caveat, cursive",
        fontSize: 36,
        color: "#2E5A27",
        fontWeight: "400",
        textAlign: "center",
        top: 25,
        left: 50,
      },
      {
        id: "header",
        key: "header",
        text: "A REHEARSAL DINNER HONORING",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 9.5,
        letterSpacing: "1.5px",
        color: "#8B0000",
        fontWeight: "600",
        textAlign: "center",
        top: 36,
        left: 50,
      },
      {
        id: "title-name",
        key: "guest",
        text: "Mallory Evans",
        fontFamily: "Playfair Display, serif",
        fontSize: 26,
        fontWeight: "700",
        color: "#1C1917",
        textAlign: "center",
        top: 45,
        left: 50,
      },
      {
        id: "datetime",
        key: "datetime",
        text: "AUGUST 24TH AT 7 PM",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "1.5px",
        color: "#57534E",
        fontWeight: "600",
        textAlign: "center",
        top: 56,
        left: 50,
      },
      {
        id: "venue",
        key: "venue",
        text: "LITTLE ITALY TRATTORIA",
        fontFamily: "Montserrat, sans-serif",
        fontSize: 11,
        letterSpacing: "2px",
        color: "#78716C",
        fontWeight: "600",
        textAlign: "center",
        top: 63,
        left: 50,
      },
    ],
  },
];

export default homeTemplatesData;
