export interface TemplateTextLayer {
  id: string;
  text: string;
  x: number; // percentage: 0 to 100
  y: number; // percentage: 0 to 100
  fontSize: number; // px
  fontFamily: string;
  color: string;
  casing: "uppercase" | "lowercase" | "capitalize" | "none";
  align: "left" | "center" | "right";
  letterSpacing: number; // px
  lineHeight: number; // multiplier e.g. 1.2
  fontWeight: string;
  isFoil?: "gold" | "rose-gold" | "silver" | null;
}

export interface PhotoSlot {
  id: string;
  x: number; // percentage center X: 0 to 100
  y: number; // percentage center Y: 0 to 100
  width: number; // px width
  height: number; // px height
  borderRadius?: string;
  imageUrl?: string | null;
  placeholderText?: string;
}

export interface NewTemplateData {
  id: string;
  type: string; // Category name
  category: string;
  tags?: string[];
  designer?: string;
  title: string;
  badge?: "Trending" | "FREE" | "PREMIUM" | string;
  subtitle: string;
  date: string;
  time: string;
  host: string;
  venue: string;
  gradient: string;
  accentColor: string;
  emoji: string;
  image: string;
  decorationImage?: string;
  description: string;
  backgroundColor: string;
  textColor: string;
  titleSize: number;
  fontWeight: string;
  fontFamily: string;
  buttonColor: string;
  buttonRadius: number;
  buttonText: string;
  textAlignment: string;
  gallery: string[];
  sections: { title: string; content: string }[];
  isLandscape?: boolean;
  swatches?: string[];
  envelopeColor: string;
  envelopeLiner: string;
  textLayers?: TemplateTextLayer[];
  photoSlot?: PhotoSlot;
}

export const NEW_TEMPLATES: NewTemplateData[] = [
  // 1. Electric Outline
  {
    id: "tpl-electric-outline",
    type: "Kids Birthday",
    category: "Birthday",
    title: "Electric Outline",
    badge: "Trending",
    subtitle: "Bruh, You In? Otto's 8th Birthday Celebration",
    date: "Sat, Aug 4",
    time: "2:30 PM",
    host: "Hosted by Otto & Family",
    venue: "Zero Gravity Park",
    gradient: "linear-gradient(135deg, #0A0B10 0%, #171923 100%)",
    accentColor: "#FFEE00",
    emoji: "⚡",
    image: "/assets/templates/electric-outline.svg",
    description: "Bruh, you in? Join us for an epic gravity-defying party with obstacle courses, neon laser games, and electric pizza!",
    backgroundColor: "#0A0B10",
    textColor: "#FFFFFF",
    titleSize: 42,
    fontWeight: "800",
    fontFamily: "Montserrat",
    buttonColor: "#FFEE00",
    buttonRadius: 9999,
    buttonText: "RSVP to Celebrate",
    textAlignment: "center",
    swatches: ["#FEF08A", "rainbow", "#F472B6"],
    envelopeColor: "#FACC15",
    envelopeLiner: "linear-gradient(135deg, #D4FF00 0%, #00D2FF 100%)",
    gallery: [],
    sections: [
      { title: "Dress Code", content: "Neon colors, sneakers & athletic gear" },
      { title: "Activities", content: "Trampoline arena, laser tag, and zero gravity obstacle race" }
    ]
  },

  // 2. Cake and Confetti (Rifle Paper Co.)
  {
    id: "tpl-cake-and-confetti",
    type: "Kids Birthday",
    category: "Birthday",
    designer: "Rifle Paper Co.",
    title: "Cake and Confetti",
    badge: "Trending",
    subtitle: "Jamie is Turning 6 & We're Having a Party",
    date: "Sat, Jul 8",
    time: "12:00 PM",
    host: "Hosted by The Arable Family",
    venue: "The Arable Residence",
    gradient: "linear-gradient(135deg, #FAF6EE 0%, #F5EFEB 100%)",
    accentColor: "#D97706",
    emoji: "🎂",
    image: "/assets/templates/cake-and-confetti.svg",
    description: "Jamie is turning 6! Please join us for an afternoon celebration filled with homemade confetti cakes, cheerful balloons, and backyard games.",
    backgroundColor: "#FAF6EE",
    textColor: "#2B2118",
    titleSize: 38,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#D97706",
    buttonRadius: 9999,
    buttonText: "RSVP to Jamie's Party",
    textAlignment: "center",
    envelopeColor: "#F7F5F0",
    envelopeLiner: "radial-gradient(ellipse at center, #E6C875 0%, #C49B45 60%, #997328 100%)",
    gallery: [],
    sections: [
      { title: "Menu", content: "Artisanal sandwiches, confetti cakes, and fresh fruit lemonades" },
      { title: "Fun & Games", content: "Piñata smashing, face painting, and balloon animals" }
    ]
  },

  // 3. Hype Night
  {
    id: "tpl-hype-night",
    type: "Kids Birthday",
    category: "Birthday",
    title: "Hype Night",
    badge: "Trending",
    subtitle: "Let's Party - Alexander's 8th Birthday",
    date: "Sun, Oct 12",
    time: "2:00 PM",
    host: "Hosted by Alexander's Family",
    venue: "Zero Gravity Adventure Park",
    gradient: "linear-gradient(135deg, #14131A 0%, #2E1065 100%)",
    accentColor: "#EC4899",
    emoji: "🎉",
    image: "/assets/templates/hype-night.svg",
    description: "Let's party! Celebrate Alexander's 8th birthday with extreme fun, arcade mania, pizza, and prizes.",
    backgroundColor: "#14131A",
    textColor: "#F8FAFC",
    titleSize: 40,
    fontWeight: "800",
    fontFamily: "Montserrat",
    buttonColor: "#EC4899",
    buttonRadius: 9999,
    buttonText: "RSVP to Roll",
    textAlignment: "center",
    isLandscape: true,
    swatches: ["split-purple-pink", "#15803D", "rainbow"],
    envelopeColor: "#F9C5D5",
    envelopeLiner: "radial-gradient(circle at 50% 50%, #FF66B2 0%, #D92080 50%, #991054 100%)",
    gallery: [],
    sections: [
      { title: "Schedule", content: "2 PM Arrival & Jump Time, 3:30 PM Pizza & Cake Celebration" }
    ]
  },

  // 4. Floating Cakes (Little Cube)
  {
    id: "tpl-floating-cakes",
    type: "Kids Birthday",
    category: "Birthday",
    designer: "Little Cube",
    title: "Floating Cakes",
    subtitle: "Mia's Turning 5 - Confetti & Cake Celebration",
    date: "Sun, Apr 19",
    time: "1:00 PM",
    host: "Hosted by The Harpers",
    venue: "The Arable Residence, Brooklyn",
    gradient: "linear-gradient(135deg, #FAF8F5 0%, #F5F0EA 100%)",
    accentColor: "#E11D48",
    emoji: "🍰",
    image: "/assets/templates/floating-cakes.svg",
    description: "Join us for a celebration full of confetti and cake! We're celebrating Mia's 5th birthday with sweet treats and playful memories.",
    backgroundColor: "#FAF8F5",
    textColor: "#2B2D31",
    titleSize: 40,
    fontWeight: "600",
    fontFamily: "Playfair Display",
    buttonColor: "#E11D48",
    buttonRadius: 9999,
    buttonText: "RSVP for Mia",
    textAlignment: "center",
    envelopeColor: "#F5CAD5",
    envelopeLiner: "sprinkles",
    gallery: [],
    sections: [
      { title: "Sweet Delights", content: "Cupcake decorating station & dessert buffet" }
    ]
  },

  // 5. Friendship Charms (Meri Meri)
  {
    id: "tpl-friendship-charms",
    type: "Kids Birthday",
    category: "Birthday",
    designer: "Meri Meri",
    title: "Friendship Charms",
    subtitle: "Fern is Turning 8 - Join Us for a Celebration",
    date: "Fri, Aug 12",
    time: "3:00 PM",
    host: "Hosted by Fern & Family",
    venue: "Our Place",
    gradient: "linear-gradient(135deg, #FAF8F2 0%, #FEE2E2 100%)",
    accentColor: "#EF4444",
    emoji: "💖",
    image: "/assets/templates/friendship-charms.svg",
    description: "Let's party! Join Fern to celebrate turning 8 with friendship bracelet crafting, charms bar, music, and strawberry treats.",
    backgroundColor: "#FAF8F2",
    textColor: "#3B271E",
    titleSize: 36,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#EF4444",
    buttonRadius: 9999,
    buttonText: "Join the Charm Party",
    textAlignment: "center",
    envelopeColor: "#F7BABA",
    envelopeLiner: "charms",
    gallery: [],
    sections: [
      { title: "DIY Bar", content: "Make your own charm bracelet to take home!" }
    ]
  },

  // 6. Sporty Frame (Meri Meri)
  {
    id: "tpl-sporty-frame",
    type: "Kids Birthday",
    category: "Birthday",
    designer: "Meri Meri",
    title: "Sporty Frame",
    subtitle: "Let's Have a Ball! Tom's Seventh Birthday",
    date: "Sun, Jul 1",
    time: "3:00 PM",
    host: "Hosted by Tom's Family",
    venue: "Mitchell Park",
    gradient: "linear-gradient(135deg, #FAF9F5 0%, #F0FDF4 100%)",
    accentColor: "#0284C7",
    emoji: "⚽",
    image: "/assets/templates/sporty-frame.svg",
    description: "Let's have a ball! Grab your sneakers and join us on the field for Tom's 7th birthday sports festival with soccer, kickball, and hot dogs.",
    backgroundColor: "#FAF9F5",
    textColor: "#0F172A",
    titleSize: 36,
    fontWeight: "800",
    fontFamily: "Montserrat",
    buttonColor: "#0284C7",
    buttonRadius: 9999,
    buttonText: "Join the Team RSVP",
    textAlignment: "center",
    envelopeColor: "#0C9744",
    envelopeLiner: "sports",
    gallery: [],
    sections: [
      { title: "Sports Clinic", content: "Soccer drills, relay races, and home-run derby" }
    ]
  },

  // 7. Pastel Garden Brunch
  {
    id: "tpl-garden-brunch",
    type: "Garden Brunch",
    category: "Wedding",
    designer: "InviteHub Studio",
    title: "Pastel Garden Brunch",
    badge: "Trending",
    subtitle: "Garden Brunch to celebrate Amanda Sanders",
    date: "Saturday, April 19",
    time: "11:00 AM",
    host: "Amanda Sanders",
    venue: "1272 Misen Avenue",
    gradient: "linear-gradient(135deg, #FDFBF7 0%, #F7F3EC 100%)",
    accentColor: "#6E885B",
    emoji: "🌸",
    image: "/assets/templates/pastel-garden-brunch.svg",
    decorationImage: "/assets/templates/pastel-garden-brunch-bg.svg",
    description: "You are cordially invited to a garden brunch to celebrate Amanda Sanders. Mimosas & light bites will be served.",
    backgroundColor: "#FDFBF7",
    textColor: "#54684E",
    titleSize: 34,
    fontWeight: "700",
    fontFamily: "Caveat",
    buttonColor: "#6E885B",
    buttonRadius: 9999,
    buttonText: "RSVP for Brunch",
    textAlignment: "center",
    envelopeColor: "#A8C3B0",
    envelopeLiner: "pink-gingham",
    gallery: [],
    sections: [
      { title: "Refreshments", content: "Mimosas, fresh juices, and artisanal light brunch bites" }
    ],
    textLayers: [
      {
        id: "layer-intro",
        text: "You are cordially invited to a",
        x: 50,
        y: 45,
        fontSize: 15,
        fontFamily: "'Caveat', cursive",
        color: "#607258",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-title",
        text: "garden brunch",
        x: 50,
        y: 53,
        fontSize: 38,
        fontFamily: "'Caveat', cursive",
        color: "#6E885B",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.1,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "to celebrate",
        x: 50,
        y: 58,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#8C9E87",
        casing: "none",
        align: "center",
        letterSpacing: 1.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-names",
        text: "Amanda Sanders",
        x: 50,
        y: 65,
        fontSize: 25,
        fontFamily: "'Playfair Display', serif",
        color: "#54684E",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-datetime",
        text: "Saturday, April 19th at 11 am",
        x: 50,
        y: 73,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#72846E",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "1272 Misen Avenue",
        x: 50,
        y: 78,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#8E9E8B",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "Mimosas & light bites will be served",
        x: 50,
        y: 83,
        fontSize: 11,
        fontFamily: "'Playfair Display', serif",
        color: "#7B8C78",
        casing: "none",
        align: "center",
        letterSpacing: 0.3,
        lineHeight: 1.2,
        fontWeight: "400",
      },
    ]
  },

  // 8. Floral Wreath Sophia Henry
  {
    id: "tpl-floral-wreath-sophia",
    type: "Wedding & Anniversary",
    category: "Wedding",
    designer: "InviteHub Studio",
    title: "Floral Wreath Sophia Henry",
    badge: "Trending",
    subtitle: "Join Us to Celebrate Sophia Henry",
    date: "Saturday, August 2",
    time: "2:00 PM",
    host: "Sophia Henry",
    venue: "50 Rose Avenue Road, Danville, AL",
    gradient: "linear-gradient(135deg, #FCFCF9 0%, #F6F5F0 100%)",
    accentColor: "#242A24",
    emoji: "🌿",
    image: "/assets/templates/floral-wreath-sophia.svg",
    decorationImage: "/assets/templates/floral-wreath-sophia-bg.svg",
    description: "Please join us to celebrate Sophia Henry on Saturday, August 2nd at 2 pm at 50 Rose Avenue Road.",
    backgroundColor: "#FCFCF9",
    textColor: "#242A24",
    titleSize: 32,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#4A5A46",
    buttonRadius: 9999,
    buttonText: "RSVP to Celebrate",
    textAlignment: "center",
    envelopeColor: "#C4A482",
    envelopeLiner: "sage-mist",
    gallery: [],
    sections: [
      { title: "Reception", content: "Cocktail reception, dinner, and dancing to follow ceremony" }
    ],
    textLayers: [
      {
        id: "layer-intro",
        text: "JOIN US TO CELEBRATE",
        x: 50,
        y: 38,
        fontSize: 10,
        fontFamily: "'Inter', sans-serif",
        color: "#7C8879",
        casing: "uppercase",
        align: "center",
        letterSpacing: 2.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-title",
        text: "SOPHIA\nHENRY",
        x: 50,
        y: 49,
        fontSize: 30,
        fontFamily: "'Cinzel', serif",
        color: "#242A24",
        casing: "uppercase",
        align: "center",
        letterSpacing: 4,
        lineHeight: 1.15,
        fontWeight: "700",
      },
      {
        id: "layer-datetime",
        text: "Saturday, August 2nd at 2pm",
        x: 50,
        y: 59,
        fontSize: 12,
        fontFamily: "'Playfair Display', serif",
        color: "#546051",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-venue",
        text: "50 Rose Avenue Road",
        x: 50,
        y: 64,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#6C7A69",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-location",
        text: "Danville, AL",
        x: 50,
        y: 68,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#7C8A79",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "500",
      },
    ]
  },

  // 9. Blue Hydrangeas Morgan & Kevin
  {
    id: "tpl-blue-hydrangeas",
    type: "Classic Wedding",
    category: "Wedding",
    designer: "InviteHub Studio",
    title: "Blue Hydrangeas Morgan & Kevin",
    badge: "Trending",
    subtitle: "Wedding of Morgan Woods & Kevin Barnes",
    date: "Saturday, April 19",
    time: "7:00 PM",
    host: "Morgan Woods & Kevin Barnes",
    venue: "The Washington Hotel, Nashville, TN",
    gradient: "linear-gradient(135deg, #FFFFFF 0%, #F9FBFD 100%)",
    accentColor: "#1E2530",
    emoji: "💐",
    image: "/assets/templates/blue-hydrangeas.svg",
    decorationImage: "/assets/templates/blue-hydrangeas-bg.svg",
    description: "Join us to celebrate the wedding of Morgan Woods & Kevin Barnes on Saturday, April 19th at 7 o'clock in the evening.",
    backgroundColor: "#FFFFFF",
    textColor: "#1E2530",
    titleSize: 34,
    fontWeight: "700",
    fontFamily: "Dancing Script",
    buttonColor: "#4B77B0",
    buttonRadius: 9999,
    buttonText: "RSVP to Wedding",
    textAlignment: "center",
    envelopeColor: "#9BB4CE",
    envelopeLiner: "silver-foil",
    gallery: [],
    sections: [
      { title: "Attire", content: "Cocktail or Formal Attire encouraged" }
    ],
    textLayers: [
      {
        id: "layer-intro",
        text: "JOIN US TO CELEBRATE",
        x: 50,
        y: 17,
        fontSize: 10,
        fontFamily: "'Inter', sans-serif",
        color: "#5A6578",
        casing: "uppercase",
        align: "center",
        letterSpacing: 2.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-title",
        text: "Morgan Woods\n&\nKevin Barnes",
        x: 50,
        y: 30,
        fontSize: 32,
        fontFamily: "'Dancing Script', cursive",
        color: "#1E2530",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-datetime",
        text: "SATURDAY, APRIL 19TH\nat 7 o'clock in the evening",
        x: 50,
        y: 44,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#3B4859",
        casing: "none",
        align: "center",
        letterSpacing: 1.2,
        lineHeight: 1.4,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "THE WASHINGTON HOTEL",
        x: 50,
        y: 52,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#2D3748",
        casing: "uppercase",
        align: "center",
        letterSpacing: 1.8,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-location",
        text: "427 Lafayette Rd, Nashville, TN",
        x: 50,
        y: 56,
        fontSize: 10,
        fontFamily: "'Inter', sans-serif",
        color: "#64748B",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
    ]
  },

  // 10. Minimalist Bella & Carter
  {
    id: "tpl-minimalist-bella-carter",
    type: "Modern Minimalist",
    category: "Wedding",
    designer: "InviteHub Studio",
    title: "Minimalist Bella & Carter",
    badge: "Trending",
    subtitle: "Wedding of Bella & Carter",
    date: "Sunday, July 18",
    time: "5:00 PM",
    host: "Bella & Carter",
    venue: "Wildwood Forest, Portland, Oregon",
    gradient: "linear-gradient(135deg, #FCFCFA 0%, #F7F6F2 100%)",
    accentColor: "#111111",
    emoji: "✨",
    image: "/assets/templates/minimalist-bella-carter.svg",
    decorationImage: "/assets/templates/minimalist-bella-carter-bg.svg",
    description: "Together with our families, we joyfully invite you to celebrate our wedding on 07/18/2026 at Wildwood Forest.",
    backgroundColor: "#FCFCFA",
    textColor: "#111111",
    titleSize: 40,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#1A1A1A",
    buttonRadius: 9999,
    buttonText: "RSVP to Wedding",
    textAlignment: "center",
    isLandscape: true,
    envelopeColor: "#ECE8E1",
    envelopeLiner: "ivory-linen",
    gallery: [],
    sections: [
      { title: "Details", content: "Outdoor ceremony followed by dinner under the stars" }
    ],
    textLayers: [
      {
        id: "layer-title",
        text: "Bella\n&\nCarter",
        x: 27,
        y: 50,
        fontSize: 40,
        fontFamily: "'Playfair Display', serif",
        color: "#1C1C1C",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.25,
        fontWeight: "700",
      },
      {
        id: "layer-intro",
        text: "Together with our families,\nwe joyfully invite you to\ncelebrate our wedding on",
        x: 73,
        y: 38,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#4B4B4B",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.45,
        fontWeight: "400",
      },
      {
        id: "layer-datetime",
        text: "07 / 18 / 2026",
        x: 73,
        y: 55,
        fontSize: 20,
        fontFamily: "'Inter', sans-serif",
        color: "#111111",
        casing: "none",
        align: "center",
        letterSpacing: 5,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-time",
        text: "at 5 o'clock in the evening",
        x: 73,
        y: 67,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#555555",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-venue",
        text: "Wildwood Forest",
        x: 73,
        y: 74,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#222222",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-location",
        text: "Portland, Oregon",
        x: 73,
        y: 79,
        fontSize: 10,
        fontFamily: "'Inter', sans-serif",
        color: "#666666",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
    ]
  },

  // 11. Blue Botanical Tiffany & Michael
  {
    id: "tpl-blue-botanical",
    type: "Botanical Classic",
    category: "Wedding",
    designer: "InviteHub Studio",
    title: "Blue Botanical Tiffany & Michael",
    badge: "Trending",
    subtitle: "Wedding of Tiffany Jones and Michael Nguyen",
    date: "Friday, August 14",
    time: "5:00 PM",
    host: "Tiffany Jones and Michael Nguyen",
    venue: "The Jones Smith Venue, Columbus, OH",
    gradient: "linear-gradient(135deg, #FFFFFF 0%, #FBFDFE 100%)",
    accentColor: "#141B26",
    emoji: "💙",
    image: "/assets/templates/blue-botanical.svg",
    decorationImage: "/assets/templates/blue-botanical-bg.svg",
    description: "Please join us for the wedding of Tiffany Jones and Michael Nguyen on Friday, August 14th @ 5 PM.",
    backgroundColor: "#FFFFFF",
    textColor: "#141B26",
    titleSize: 26,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#1D4ED8",
    buttonRadius: 9999,
    buttonText: "RSVP to Wedding",
    textAlignment: "center",
    envelopeColor: "#102A54",
    envelopeLiner: "silver-foil",
    gallery: [],
    sections: [
      { title: "Ceremony & Reception", content: "Evening ceremony with dinner and dancing under fairy lights" }
    ],
    textLayers: [
      {
        id: "layer-intro",
        text: "Please join us for",
        x: 50,
        y: 28,
        fontSize: 22,
        fontFamily: "'Dancing Script', cursive",
        color: "#3B4A60",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-title",
        text: "TIFFANY JONES\nand\nMICHAEL NGUYEN",
        x: 50,
        y: 41,
        fontSize: 21,
        fontFamily: "'Cinzel', serif",
        color: "#141B26",
        casing: "uppercase",
        align: "center",
        letterSpacing: 3,
        lineHeight: 1.35,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "Please join us for this special occasion.",
        x: 50,
        y: 57,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#4B586E",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-datetime",
        text: "Friday, August 14th @ 5 PM",
        x: 50,
        y: 63,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#243042",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "The Jones Smith Venue",
        x: 50,
        y: 68,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#4B586E",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-location",
        text: "123 Floral Street St, Columbus, OH",
        x: 50,
        y: 72,
        fontSize: 10,
        fontFamily: "'Inter', sans-serif",
        color: "#6B798F",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
    ]
  },

  // 12. Winter Foliage
  {
    id: "tpl-winter-foliage",
    type: "Baby Shower",
    category: "Baby Shower",
    tags: ["Baby Shower", "All"],
    designer: "InviteHub Studio",
    title: "Winter Foliage",
    badge: "Trending",
    subtitle: "Julia's Very Merry Baby Shower",
    date: "Saturday, December 12",
    time: "2:00 PM",
    host: "Julia",
    venue: "The Holly & Hearth Bistro",
    gradient: "linear-gradient(135deg, #FCFAF5 0%, #F2ECE0 100%)",
    accentColor: "#751824",
    emoji: "🌿",
    image: "/assets/templates/winter-foliage.svg",
    decorationImage: "/assets/templates/winter-foliage-bg.svg",
    description: "Please join us for Julia's Very Merry Baby Shower honoring baby girl Harper on Saturday, December 12th at 2:00 PM.",
    backgroundColor: "#FCFAF5",
    textColor: "#203424",
    titleSize: 36,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#751824",
    buttonRadius: 9999,
    buttonText: "RSVP to Baby Shower",
    textAlignment: "center",
    envelopeColor: "#C93B4E",
    envelopeLiner: "gold-foil",
    gallery: [],
    sections: [
      { title: "Celebration Details", content: "Cozy winter treats, hot cocoa bar, and merry holiday games" }
    ],
    textLayers: [
      {
        id: "layer-greeting",
        text: "PLEASE JOIN US FOR",
        x: 50,
        y: 34,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#6B7869",
        casing: "uppercase",
        align: "center",
        letterSpacing: 3,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-celebrant",
        text: "Julia's Very Merry\nBaby Shower",
        x: 50,
        y: 44,
        fontSize: 34,
        fontFamily: "'Playfair Display', serif",
        color: "#751824",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "HONORING BABY GIRL HARPER",
        x: 50,
        y: 53,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#7B8878",
        casing: "uppercase",
        align: "center",
        letterSpacing: 2,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-datetime",
        text: "SATURDAY, DECEMBER 12TH\nAT 2:00 IN THE AFTERNOON",
        x: 50,
        y: 63,
        fontSize: 14,
        fontFamily: "'Playfair Display', serif",
        color: "#203424",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.35,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "The Holly & Hearth Bistro",
        x: 50,
        y: 73,
        fontSize: 15,
        fontFamily: "'Playfair Display', serif",
        color: "#751824",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-address",
        text: "452 Wintergreen Way, Aspen, CO",
        x: 50,
        y: 77,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#60705E",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "RSVP to Sarah by Dec 1st • 555-0192",
        x: 50,
        y: 84,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#751824",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "500",
      },
    ]
  },

  // 13. Watercolor Eucalyptus Wreath
  {
    id: "tpl-watercolor-eucalyptus-wreath",
    type: "Baby Shower",
    category: "Baby Shower",
    tags: ["Baby Shower", "All"],
    designer: "InviteHub Studio",
    title: "Watercolor Eucalyptus Wreath",
    badge: "Trending",
    subtitle: "WELCOME BABY! Baby Oliver Thompson",
    date: "Sunday, May 17",
    time: "1:00 PM",
    host: "Jessica Thompson",
    venue: "The Botanical Conservatory",
    gradient: "linear-gradient(135deg, #FCFCFA 0%, #F2F4EF 100%)",
    accentColor: "#3D5340",
    emoji: "🌱",
    image: "/assets/templates/watercolor-eucalyptus-wreath.svg",
    decorationImage: "/assets/templates/watercolor-eucalyptus-wreath-bg.svg",
    description: "Welcome Baby! Please join us to celebrate Baby Oliver Thompson and mom-to-be Jessica on Sunday, May 17th at 1:00 PM.",
    backgroundColor: "#FCFCFA",
    textColor: "#253526",
    titleSize: 34,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#3D5340",
    buttonRadius: 9999,
    buttonText: "RSVP to Welcome Baby",
    textAlignment: "center",
    envelopeColor: "#A8BCA9",
    envelopeLiner: "sage-mist",
    gallery: [],
    sections: [
      { title: "Celebration", content: "Afternoon botanical tea, sweet macarons, and mimosa bar" }
    ],
    textLayers: [
      {
        id: "layer-greeting",
        text: "WELCOME\nBABY!",
        x: 50,
        y: 32,
        fontSize: 26,
        fontFamily: "'Cinzel', serif",
        color: "#3D5340",
        casing: "uppercase",
        align: "center",
        letterSpacing: 4,
        lineHeight: 1.25,
        fontWeight: "700",
      },
      {
        id: "layer-intro",
        text: "PLEASE JOIN US TO CELEBRATE",
        x: 50,
        y: 41,
        fontSize: 10,
        fontFamily: "'Inter', sans-serif",
        color: "#758E76",
        casing: "uppercase",
        align: "center",
        letterSpacing: 2.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-celebrant",
        text: "Baby Oliver Thompson",
        x: 50,
        y: 58,
        fontSize: 32,
        fontFamily: "'Playfair Display', serif",
        color: "#253526",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "HONORING MOM-TO-BE JESSICA",
        x: 50,
        y: 64,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#6A826B",
        casing: "uppercase",
        align: "center",
        letterSpacing: 1.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-datetime",
        text: "SUNDAY, MAY 17TH AT 1:00 PM",
        x: 50,
        y: 71,
        fontSize: 14,
        fontFamily: "'Playfair Display', serif",
        color: "#2E4030",
        casing: "uppercase",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "The Botanical Conservatory",
        x: 50,
        y: 77,
        fontSize: 14,
        fontFamily: "'Playfair Display', serif",
        color: "#3D5340",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-address",
        text: "784 Meadow Vista Lane, Portland, OR",
        x: 50,
        y: 80.5,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#627763",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "Registered at Target & Babylist • RSVP to 555-0144",
        x: 50,
        y: 86.5,
        fontSize: 10.5,
        fontFamily: "'Inter', sans-serif",
        color: "#4B634E",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
    ]
  },

  // 14. Disney's Winnie the Pooh: So Sweet
  {
    id: "tpl-winnie-the-pooh-so-sweet",
    type: "Baby Shower",
    category: "Baby Shower",
    tags: ["Baby Shower", "All"],
    designer: "Disney / InviteHub Studio",
    title: "Disney's Winnie the Pooh: So Sweet",
    badge: "Trending",
    subtitle: "A little hunny is on the way! Amanda Jones",
    date: "Saturday, September 26",
    time: "2:00 PM",
    host: "Amanda Jones",
    venue: "Hundred Acre Garden Cafe",
    gradient: "linear-gradient(135deg, #FCF8EE 0%, #EFE1BF 100%)",
    accentColor: "#9C5A14",
    emoji: "🍯",
    image: "/assets/templates/winnie-the-pooh-so-sweet.svg",
    decorationImage: "/assets/templates/winnie-the-pooh-so-sweet-bg.svg",
    description: "A little hunny is on the way! Join us for a So Sweet Baby Shower celebrating Amanda Jones and the upcoming arrival of baby Noah.",
    backgroundColor: "#FCF8EE",
    textColor: "#523211",
    titleSize: 32,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#F5B82E",
    buttonRadius: 9999,
    buttonText: "RSVP for Hunny Shower",
    textAlignment: "center",
    envelopeColor: "#E8C87A",
    envelopeLiner: "gold-foil",
    photoSlot: {
      id: "pooh-baby-photo",
      x: 50,
      y: 27,
      width: 140,
      height: 140,
      borderRadius: "9999px",
      imageUrl: "/assets/templates/pooh-baby-photo-placeholder.svg",
      placeholderText: "Click to replace baby photo",
    },
    gallery: [],
    sections: [
      { title: "Sweet Delights", content: "Hunny-drizzled waffles, afternoon tea, and storybook games" }
    ],
    textLayers: [
      {
        id: "layer-greeting",
        text: "A little hunny is on the way!",
        x: 50,
        y: 11,
        fontSize: 22,
        fontFamily: "'Caveat', cursive",
        color: "#A8681B",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-celebrant",
        text: "So Sweet Baby Shower",
        x: 50,
        y: 43,
        fontSize: 32,
        fontFamily: "'Playfair Display', serif",
        color: "#523211",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-honoree",
        text: "FOR AMANDA JONES",
        x: 50,
        y: 48,
        fontSize: 13,
        fontFamily: "'Inter', sans-serif",
        color: "#9C5A14",
        casing: "uppercase",
        align: "center",
        letterSpacing: 2,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "Celebrating the sweet arrival of baby Noah",
        x: 50,
        y: 53.5,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#6E5031",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-datetime",
        text: "SATURDAY, SEPTEMBER 26TH\nAT 2:00 IN THE AFTERNOON",
        x: 50,
        y: 63.5,
        fontSize: 14,
        fontFamily: "'Playfair Display', serif",
        color: "#3D2409",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.35,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "Hundred Acre Garden Cafe",
        x: 50,
        y: 72.5,
        fontSize: 15,
        fontFamily: "'Playfair Display', serif",
        color: "#523211",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-address",
        text: "100 Wood Cottage Rd, Pasadena, CA",
        x: 50,
        y: 76,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#7D5C3B",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "RSVP to Kanga & Roo by Sept 15 • 555-0188",
        x: 50,
        y: 83.5,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#8C5316",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
    ]
  },

  // 15. Camellia Fields
  {
    id: "tpl-camellia-fields",
    type: "Baby Shower",
    category: "Baby Shower",
    tags: ["Baby Shower", "All"],
    designer: "InviteHub Studio",
    title: "Camellia Fields",
    badge: "Trending",
    subtitle: "Cassidy Anderson Baby Shower Celebration",
    date: "Saturday, June 20",
    time: "11:30 AM",
    host: "Cassidy Anderson",
    venue: "The Rosewood Manor Garden",
    gradient: "linear-gradient(135deg, #FCF8F7 0%, #F3E9E7 100%)",
    accentColor: "#59252F",
    emoji: "🌸",
    image: "/assets/templates/camellia-fields.svg",
    decorationImage: "/assets/templates/camellia-fields-bg.svg",
    description: "Please join us to celebrate Cassidy Anderson and the upcoming arrival of her baby girl on Saturday, June 20th at 11:30 AM.",
    backgroundColor: "#FCF8F7",
    textColor: "#421E25",
    titleSize: 40,
    fontWeight: "700",
    fontFamily: "Playfair Display",
    buttonColor: "#8A4854",
    buttonRadius: 9999,
    buttonText: "RSVP for Cassidy",
    textAlignment: "center",
    envelopeColor: "#EABAC1",
    envelopeLiner: "pink-gingham",
    gallery: [],
    sections: [
      { title: "Garden Party", content: "Floral mocktails, artisanal pastries, and garden games" }
    ],
    textLayers: [
      {
        id: "layer-greeting",
        text: "PLEASE JOIN US TO CELEBRATE",
        x: 50,
        y: 26,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#8C5C64",
        casing: "uppercase",
        align: "center",
        letterSpacing: 3,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-celebrant",
        text: "Cassidy Anderson",
        x: 50,
        y: 35,
        fontSize: 40,
        fontFamily: "'Playfair Display', serif",
        color: "#421E25",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.15,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "AND THE UPCOMING ARRIVAL OF HER BABY GIRL",
        x: 50,
        y: 41,
        fontSize: 12,
        fontFamily: "'Inter', sans-serif",
        color: "#7C4B54",
        casing: "uppercase",
        align: "center",
        letterSpacing: 1.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
      {
        id: "layer-datetime",
        text: "SATURDAY, JUNE 20TH\nAT 11:30 IN THE MORNING",
        x: 50,
        y: 53.5,
        fontSize: 14.5,
        fontFamily: "'Playfair Display', serif",
        color: "#3D1C23",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.35,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "The Rosewood Manor Garden",
        x: 50,
        y: 65.5,
        fontSize: 16,
        fontFamily: "'Playfair Display', serif",
        color: "#59252F",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-address",
        text: "324 Camellia Drive, Charleston, SC",
        x: 50,
        y: 69,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#7D4B54",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "RSVP to Chloe at 555-0167 • Registered at Pottery Barn Kids",
        x: 50,
        y: 78,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#8A4854",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
    ]
  },

  // 16. Bountiful Bouquet
  {
    id: "tpl-bountiful-bouquet",
    type: "Baby Shower",
    category: "Baby Shower",
    tags: ["Baby Shower", "All"],
    designer: "InviteHub Studio",
    title: "Bountiful Bouquet",
    badge: "Trending",
    subtitle: "AMBER & TAYLOR Baby Shower",
    date: "Sunday, August 16",
    time: "2:00 PM",
    host: "Amber & Taylor",
    venue: "The Glasshouse Loft",
    gradient: "linear-gradient(135deg, #FCFCFA 0%, #F4F4EE 100%)",
    accentColor: "#1C241E",
    emoji: "💐",
    image: "/assets/templates/bountiful-bouquet.svg",
    decorationImage: "/assets/templates/bountiful-bouquet-bg.svg",
    description: "Join us for a baby shower honoring Amber & Taylor as they prepare to welcome their little one on Sunday, August 16th at 2:00 PM.",
    backgroundColor: "#FCFCFA",
    textColor: "#1C241E",
    titleSize: 32,
    fontWeight: "700",
    fontFamily: "Cinzel",
    buttonColor: "#2D3B2E",
    buttonRadius: 9999,
    buttonText: "RSVP for Amber & Taylor",
    textAlignment: "center",
    envelopeColor: "#D0D9CE",
    envelopeLiner: "ivory-linen",
    gallery: [],
    sections: [
      { title: "Celebration", content: "Cocktails, mocktails, light bites, and rooftop city views" }
    ],
    textLayers: [
      {
        id: "layer-greeting",
        text: "JOIN US FOR A BABY SHOWER HONORING",
        x: 50,
        y: 26,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#7A8778",
        casing: "uppercase",
        align: "center",
        letterSpacing: 3.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-celebrant",
        text: "AMBER & TAYLOR",
        x: 50,
        y: 36,
        fontSize: 32,
        fontFamily: "'Cinzel', serif",
        color: "#1C241E",
        casing: "uppercase",
        align: "center",
        letterSpacing: 5,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "as they prepare to welcome their little one",
        x: 50,
        y: 42,
        fontSize: 14,
        fontFamily: "'Playfair Display', serif",
        color: "#586957",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-datetime",
        text: "SUNDAY, AUGUST 16TH\n2:00 TO 5:00 IN THE AFTERNOON",
        x: 50,
        y: 56,
        fontSize: 13.5,
        fontFamily: "'Inter', sans-serif",
        color: "#2D3B2E",
        casing: "none",
        align: "center",
        letterSpacing: 1.8,
        lineHeight: 1.4,
        fontWeight: "600",
      },
      {
        id: "layer-venue",
        text: "The Glasshouse Loft",
        x: 50,
        y: 69,
        fontSize: 15.5,
        fontFamily: "'Cinzel', serif",
        color: "#1C241E",
        casing: "none",
        align: "center",
        letterSpacing: 2,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-address",
        text: "89 Mercer Street, New York, NY",
        x: 50,
        y: 72.5,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#6A7A6B",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "RSVP by August 1st to taylor.amber@example.com",
        x: 50,
        y: 81.5,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#4B5E4D",
        casing: "none",
        align: "center",
        letterSpacing: 0.6,
        lineHeight: 1.2,
        fontWeight: "500",
      },
    ]
  },

  // 17. Orchid & Geranium
  {
    id: "tpl-orchid-geranium",
    type: "Baby Shower",
    category: "Baby Shower",
    tags: ["Baby Shower", "All"],
    designer: "InviteHub Studio",
    title: "Orchid & Geranium",
    badge: "Trending",
    subtitle: "Brittany Anderson Baby Shower Celebration",
    date: "Saturday, October 10",
    time: "1:00 PM",
    host: "Brittany Anderson",
    venue: "The Palm Terrace Pavilion",
    gradient: "linear-gradient(135deg, #FFFDF9 0%, #F5ECE4 100%)",
    accentColor: "#7E1343",
    emoji: "🌺",
    image: "/assets/templates/orchid-geranium.svg",
    decorationImage: "/assets/templates/orchid-geranium-bg.svg",
    description: "A vibrant baby shower celebration for Brittany Anderson! Join us on Saturday, October 10th at 1:00 PM at The Palm Terrace Pavilion.",
    backgroundColor: "#FFFDF9",
    textColor: "#3D1222",
    titleSize: 42,
    fontWeight: "700",
    fontFamily: "Dancing Script",
    buttonColor: "#800D41",
    buttonRadius: 9999,
    buttonText: "RSVP for Brittany",
    textAlignment: "center",
    envelopeColor: "#E28AA8",
    envelopeLiner: "electric-gradient",
    gallery: [],
    sections: [
      { title: "Celebration", content: "Tropical cocktails, mocktails, light bites, and celebration cake" }
    ],
    textLayers: [
      {
        id: "layer-greeting",
        text: "A BABY SHOWER CELEBRATION FOR",
        x: 50,
        y: 26,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#913B56",
        casing: "uppercase",
        align: "center",
        letterSpacing: 3.5,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-celebrant",
        text: "Brittany Anderson",
        x: 50,
        y: 35,
        fontSize: 42,
        fontFamily: "'Dancing Script', cursive",
        color: "#7E1343",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.15,
        fontWeight: "700",
      },
      {
        id: "layer-subtitle",
        text: "LET'S SHOWER BRITTANY WITH LOVE BEFORE BABY ARRIVES!",
        x: 50,
        y: 41,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#8F3255",
        casing: "uppercase",
        align: "center",
        letterSpacing: 1.5,
        lineHeight: 1.2,
        fontWeight: "600",
      },
      {
        id: "layer-datetime",
        text: "SATURDAY, OCTOBER 10TH\nAT 1:00 IN THE AFTERNOON",
        x: 50,
        y: 53.5,
        fontSize: 14.5,
        fontFamily: "'Playfair Display', serif",
        color: "#3D1222",
        casing: "none",
        align: "center",
        letterSpacing: 1,
        lineHeight: 1.35,
        fontWeight: "700",
      },
      {
        id: "layer-venue",
        text: "The Palm Terrace Pavilion",
        x: 50,
        y: 65.5,
        fontSize: 16,
        fontFamily: "'Playfair Display', serif",
        color: "#800D41",
        casing: "none",
        align: "center",
        letterSpacing: 0.8,
        lineHeight: 1.2,
        fontWeight: "700",
      },
      {
        id: "layer-address",
        text: "510 Coral Way, Miami, FL",
        x: 50,
        y: 69,
        fontSize: 11.5,
        fontFamily: "'Inter', sans-serif",
        color: "#6E2C42",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "400",
      },
      {
        id: "layer-rsvp",
        text: "RSVP by Sept 25 to 555-0139 • Light bites & cocktails served",
        x: 50,
        y: 78,
        fontSize: 11,
        fontFamily: "'Inter', sans-serif",
        color: "#A82855",
        casing: "none",
        align: "center",
        letterSpacing: 0.5,
        lineHeight: 1.2,
        fontWeight: "500",
      },
    ]
  },
];

export const NEW_TEMPLATES_CARD_ITEMS = NEW_TEMPLATES.map((t) => ({
  id: t.id,
  type: t.type,
  category: t.category,
  tags: t.tags,
  designer: t.designer,
  title: t.title,
  badge: t.badge,
  subtitle: t.subtitle,
  date: t.date,
  time: t.time,
  host: t.host,
  venue: t.venue,
  gradient: t.gradient,
  accentColor: t.accentColor,
  emoji: t.emoji,
  image: t.image,
  description: t.description,
  backgroundColor: t.backgroundColor,
  textColor: t.textColor,
  buttonColor: t.buttonColor,
  buttonText: t.buttonText,
  gallery: t.gallery,
  sections: t.sections,
  isLandscape: t.isLandscape,
  swatches: t.swatches,
  envelopeColor: t.envelopeColor,
  envelopeLiner: t.envelopeLiner,
  photoSlot: t.photoSlot,
}));

export const NEW_TEMPLATES_CONFIG: Record<string, NewTemplateData> = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = {
    ...t,
  };
  return acc;
}, {} as Record<string, NewTemplateData>);

export const NEW_TEMPLATE_DEFAULTS = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = {
    ...t,
  };
  return acc;
}, {} as Record<string, any>);

export const getTemplateConfig = (templateId?: string | null): NewTemplateData | null => {
  if (!templateId) return null;
  if (NEW_TEMPLATES_CONFIG[templateId]) {
    return NEW_TEMPLATES_CONFIG[templateId];
  }
  // Try case-insensitive or trim search
  const cleanId = templateId.trim().toLowerCase();
  const matchedKey = Object.keys(NEW_TEMPLATES_CONFIG).find(
    (k) => k.toLowerCase() === cleanId
  );
  if (matchedKey) {
    return NEW_TEMPLATES_CONFIG[matchedKey];
  }
  return null;
};

export const NEW_FALLBACK_TEMPLATES = NEW_TEMPLATES.map((t) => ({
  id: t.id,
  name: t.title,
  category: t.category,
  badge: t.badge,
  content: JSON.stringify({
    gradient: t.gradient,
    accentColor: t.accentColor,
    emoji: t.emoji,
    host: t.host,
    venue: t.venue,
    description: t.description,
    image: t.image,
  }),
  isPremium: false,
}));

export const NEW_TEMPLATE_IMAGES = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = t.image;
  return acc;
}, {} as Record<string, string>);

export const NEW_TEMPLATE_STYLES = NEW_TEMPLATES.reduce((acc, t) => {
  acc[t.id] = {
    gradient: t.gradient,
    accentColor: t.accentColor,
    emoji: t.emoji,
    imageUrl: t.image,
    host: t.host,
    venue: t.venue,
    description: t.description,
  };
  return acc;
}, {} as Record<string, any>);
